import EconCSLib.SocialChoice.Voting.STV
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.List.Count
import Mathlib.Data.Nat.Choose.Sum

/-!
# STV Outcome Structures

Reusable paper-neutral structures for the final order or winner/loser sequence
produced by an STV/RCV trace.

The key application-level obligation for strategy analyses is usually a replay
theorem: a proposed final structure is valid for the deterministic trace
generated by a profile and tie-breaking convention. This module provides the
shared vocabulary for that obligation without choosing a concrete replay
relation.

## Main declarations

- `FinalOrder`
- `WinLossStructure`
- `RoundOutcome`
- `OrderSequenceStructure`
- `StructureConstraints`
- `classifierStructureConstraints`
- `StructureConstraintCharacterization`
- `StructurePartition`
- `StructureOutcomeAgreement`
- `StructureReplay`
-/

namespace EconCSLib
namespace SocialChoice
namespace Voting

/-- A final ordered list of candidates, with no duplicate candidates. -/
structure FinalOrder (Candidate : Type*) where
  order : List Candidate
  nodup_order : order.Nodup

namespace FinalOrder

/-- The first `k` candidates in a final order, interpreted as elected winners. -/
def topCandidates {Candidate : Type*} [DecidableEq Candidate]
    (finalOrder : FinalOrder Candidate) (k : ℕ) : Finset Candidate :=
  (finalOrder.order.take k).toFinset

end FinalOrder

/-- A winner/loser split produced by a voting trace. -/
structure WinLossStructure (Candidate : Type*) where
  winners : Finset Candidate
  losers : Finset Candidate
  disjoint : Disjoint winners losers

namespace WinLossStructure

/-- Number of final winners satisfying a party predicate. -/
def partyWinnerCount {Candidate : Type*} [DecidableEq Candidate]
    (outcome : WinLossStructure Candidate) (party : Candidate → Prop)
    [DecidablePred party] : ℕ :=
  (outcome.winners.filter party).card

/--
If a certified quota-winner set is contained in the final winners of a party,
then its cardinality is no larger than that party's final seat count.
-/
theorem quotaWinnerCard_le_partyWinnerCount_of_subset {Candidate : Type*}
    [DecidableEq Candidate] {outcome : WinLossStructure Candidate}
    {party : Candidate → Prop} [DecidablePred party]
    {quotaWinners : Finset Candidate}
    (hsubset : quotaWinners ⊆ outcome.winners.filter party) :
    quotaWinners.card ≤ outcome.partyWinnerCount party := by
  exact Finset.card_le_card hsubset

/--
Same as `quotaWinnerCard_le_partyWinnerCount_of_subset`, stated for a numeric
quota-winner count already proved equal to the certified set cardinality.
-/
theorem quotaCount_le_partyWinnerCount_of_subset {Candidate : Type*}
    [DecidableEq Candidate] {outcome : WinLossStructure Candidate}
    {party : Candidate → Prop} [DecidablePred party]
    {quotaWinners : Finset Candidate} {quotaCount : ℕ}
    (hcount : quotaCount = quotaWinners.card)
    (hsubset : quotaWinners ⊆ outcome.winners.filter party) :
    quotaCount ≤ outcome.partyWinnerCount party := by
  rw [hcount]
  exact quotaWinnerCard_le_partyWinnerCount_of_subset hsubset

end WinLossStructure

/-- Per-round outcome label in an order-and-sequence structure. -/
inductive RoundOutcome where
  | win
  | lose
  deriving DecidableEq, Repr

namespace RoundOutcome

/-- Boolean indicator for round-winning labels. -/
def isWin : RoundOutcome → Bool
  | win => true
  | lose => false

/-- Boolean indicator for round-losing labels. -/
def isLoss : RoundOutcome → Bool
  | win => false
  | lose => true

/-- Number of round-winning labels in an STV order/sequence path. -/
def winCount (sequence : List RoundOutcome) : ℕ :=
  sequence.countP isWin

/-- Number of consecutive losing labels at the start of an STV order/sequence path. -/
def initialLossCount : List RoundOutcome → ℕ
  | [] => 0
  | win :: _rest => 0
  | lose :: rest => initialLossCount rest + 1

/--
The first `length` labels of a round-outcome sequence are losses.

This is the paper-neutral form of an "initial loss prefix" witness.  It is
stated by equality with a replicated losing prefix so it also records that the
sequence is long enough.
-/
def HasInitialLossPrefix (sequence : List RoundOutcome) (length : ℕ) : Prop :=
  sequence.take length = List.replicate length lose

/-- The number of round-winning labels is at most the sequence length. -/
theorem winCount_le_length (sequence : List RoundOutcome) :
    winCount sequence ≤ sequence.length := by
  simpa [winCount] using List.countP_le_length (l := sequence) (p := isWin)

/-- A concrete losing prefix gives a lower bound on the initial-loss count. -/
theorem length_le_initialLossCount_of_hasInitialLossPrefix
    {sequence : List RoundOutcome} {length : ℕ}
    (hprefix : HasInitialLossPrefix sequence length) :
    length ≤ initialLossCount sequence := by
  induction sequence generalizing length with
  | nil =>
      cases length with
      | zero =>
          simp
      | succ length =>
          simp [HasInitialLossPrefix] at hprefix
  | cons outcome rest ih =>
      cases length with
      | zero =>
          simp
      | succ length =>
          cases outcome with
          | win =>
              change
                win :: rest.take length =
                  lose :: List.replicate length lose at hprefix
              cases (List.cons.inj hprefix).1
          | lose =>
              change
                lose :: rest.take length =
                  lose :: List.replicate length lose at hprefix
              have htail : rest.take length = List.replicate length lose :=
                (List.cons.inj hprefix).2
              change length + 1 ≤ initialLossCount rest + 1
              exact Nat.succ_le_succ
                (ih (by simpa [HasInitialLossPrefix] using htail))

/-- Positions at which a fixed-length round-outcome sequence records a win. -/
def winPositions {rounds : ℕ} (sequence : Fin rounds → RoundOutcome) :
    Finset (Fin rounds) :=
  Finset.univ.filter fun i => sequence i = win

/--
Win-position sets whose cardinality is between one and `maxWins`.

This is the reusable combinatorial object behind STV/RCV statements that bound
the number of feasible win/loss sequences by choosing the positions occupied by
round wins.
-/
def feasibleWinPositionSets (rounds maxWins : ℕ) : Finset (Finset (Fin rounds)) :=
  (Finset.Icc 1 maxWins).biUnion fun wins =>
    (Finset.univ : Finset (Fin rounds)).powersetCard wins

/-- A fixed-length win/loss sequence is determined by its win positions. -/
theorem winPositions_injective (rounds : ℕ) :
    Function.Injective (winPositions (rounds := rounds)) := by
  intro sequence otherSequence hpositions
  funext i
  have hmem :
      i ∈ winPositions sequence ↔ i ∈ winPositions otherSequence := by
    rw [hpositions]
  simp [winPositions] at hmem
  cases hseq : sequence i <;> cases hother : otherSequence i <;> simp [hseq, hother] at hmem ⊢

/--
Every fixed-length win/loss sequence with between one and `maxWins` wins maps to
the corresponding bounded family of win-position sets.
-/
theorem winPositions_mem_feasibleWinPositionSets_of_card_bounds
    {rounds maxWins : ℕ} {sequence : Fin rounds → RoundOutcome}
    (hpos : 1 ≤ (winPositions sequence).card)
    (hle : (winPositions sequence).card ≤ maxWins) :
    winPositions sequence ∈ feasibleWinPositionSets rounds maxWins := by
  unfold feasibleWinPositionSets
  refine Finset.mem_biUnion.mpr
    ⟨(winPositions sequence).card, Finset.mem_Icc.mpr ⟨hpos, hle⟩, ?_⟩
  simp [winPositions]

/--
The family of bounded win-position sets has cardinality at most the corresponding
sum of binomial coefficients.
-/
theorem card_feasibleWinPositionSets_le_sum_choose (rounds maxWins : ℕ) :
    (feasibleWinPositionSets rounds maxWins).card ≤
      ∑ wins ∈ Finset.Icc 1 maxWins, rounds.choose wins := by
  unfold feasibleWinPositionSets
  calc
    ((Finset.Icc 1 maxWins).biUnion fun wins =>
        (Finset.univ : Finset (Fin rounds)).powersetCard wins).card
        ≤ ∑ wins ∈ Finset.Icc 1 maxWins,
            ((Finset.univ : Finset (Fin rounds)).powersetCard wins).card :=
          Finset.card_biUnion_le
    _ = ∑ wins ∈ Finset.Icc 1 maxWins, rounds.choose wins := by
          refine Finset.sum_congr rfl ?_
          intro wins _hwins
          simp

/--
Any finite family of fixed-length win/loss sequences with between one and
`maxWins` wins has size bounded by the corresponding binomial sum.
-/
theorem card_le_sum_choose_of_winPositions_card_bounds
    {rounds maxWins : ℕ} {sequences : Finset (Fin rounds → RoundOutcome)}
    (hbounds : ∀ sequence ∈ sequences,
      1 ≤ (winPositions sequence).card ∧
        (winPositions sequence).card ≤ maxWins) :
    sequences.card ≤ ∑ wins ∈ Finset.Icc 1 maxWins, rounds.choose wins := by
  calc
    sequences.card ≤ (feasibleWinPositionSets rounds maxWins).card := by
      refine Finset.card_le_card_of_injOn (fun sequence => winPositions sequence) ?_ ?_
      · intro sequence hsequence
        exact winPositions_mem_feasibleWinPositionSets_of_card_bounds
          (hbounds sequence hsequence).1 (hbounds sequence hsequence).2
      · intro sequence hsequence otherSequence hotherSequence hpositions
        exact winPositions_injective rounds hpositions
    _ ≤ ∑ wins ∈ Finset.Icc 1 maxWins, rounds.choose wins :=
      card_feasibleWinPositionSets_le_sum_choose rounds maxWins

end RoundOutcome

namespace RoundOutcome

/-- The round-outcome label contributed by an STV trace step kind, if any. -/
def ofStepKind? : StepKind → Option RoundOutcome
  | StepKind.elect => some win
  | StepKind.eliminate => some lose
  | StepKind.transfer => none
  | StepKind.finish => none

@[simp] theorem ofStepKind?_elect :
    ofStepKind? StepKind.elect = some win :=
  rfl

@[simp] theorem ofStepKind?_eliminate :
    ofStepKind? StepKind.eliminate = some lose :=
  rfl

@[simp] theorem ofStepKind?_transfer :
    ofStepKind? StepKind.transfer = none :=
  rfl

@[simp] theorem ofStepKind?_finish :
    ofStepKind? StepKind.finish = none :=
  rfl

end RoundOutcome

namespace STVStep

/-- The round-outcome label contributed by a trace step, if the step is a round outcome. -/
def roundOutcome? {Candidate : Type*} (step : STVStep Candidate) :
    Option RoundOutcome :=
  RoundOutcome.ofStepKind? step.kind

end STVStep

namespace STVTrace

/-- The win/loss round-outcome sequence obtained from a trace's elect/eliminate steps. -/
def roundOutcomeSequence {Candidate : Type*}
    (trace : STVTrace Candidate) : List RoundOutcome :=
  trace.steps.filterMap STVStep.roundOutcome?

/--
The first `length` trace steps are elimination steps, and there are at least
that many steps.
-/
def HasInitialEliminationPrefix {Candidate : Type*}
    (trace : STVTrace Candidate) (length : ℕ) : Prop :=
  length ≤ trace.steps.length ∧
    ∀ step, step ∈ trace.steps.take length → step.kind = StepKind.eliminate

/--
The first trace steps eliminate exactly the focused candidates listed in
`lossPrefix`.

This source-shaped predicate is useful when a paper algorithm returns an
ordered prefix of candidates and the concrete STV trace must be shown to
eliminate those candidates before any election step.
-/
def HasInitialEliminationFocusPrefix {Candidate : Type*}
    (trace : STVTrace Candidate) (lossPrefix : List Candidate) : Prop :=
  lossPrefix.length ≤ trace.steps.length ∧
    (trace.steps.take lossPrefix.length).map STVStep.focus =
      lossPrefix.map some ∧
    ∀ step, step ∈ trace.steps.take lossPrefix.length →
      step.kind = StepKind.eliminate

/--
An initial focused-elimination prefix supplies the weaker initial-elimination
prefix needed by win/loss sequence reasoning.
-/
theorem hasInitialEliminationPrefix_of_initialEliminationFocusPrefix
    {Candidate : Type*} {trace : STVTrace Candidate}
    {lossPrefix : List Candidate}
    (hprefix : trace.HasInitialEliminationFocusPrefix lossPrefix) :
    trace.HasInitialEliminationPrefix lossPrefix.length := by
  rcases hprefix with ⟨hlen, _hfocus, hkind⟩
  exact ⟨hlen, hkind⟩

/--
Index-wise trace facts package into the focused initial-elimination prefix
predicate. This is the bridge used when an executable STV run proves the first
`lossPrefix.length` trace steps one round at a time.
-/
theorem hasInitialEliminationFocusPrefix_of_getElem
    {Candidate : Type*} {trace : STVTrace Candidate}
    {lossPrefix : List Candidate}
    (hlen : lossPrefix.length ≤ trace.steps.length)
    (hfocus :
      ∀ i : Fin lossPrefix.length,
        (trace.steps.get
          ⟨i.1, Nat.lt_of_lt_of_le i.2 hlen⟩).focus =
          some (lossPrefix.get i))
    (hkind :
      ∀ i : Fin lossPrefix.length,
        (trace.steps.get
          ⟨i.1, Nat.lt_of_lt_of_le i.2 hlen⟩).kind =
          StepKind.eliminate) :
    trace.HasInitialEliminationFocusPrefix lossPrefix := by
  refine ⟨hlen, ?_, ?_⟩
  · apply List.ext_getElem
    · simp [Nat.min_eq_left hlen]
    · intro n hleft hright
      have hn_loss : n < lossPrefix.length := by
        simpa [Nat.min_eq_left hlen] using hleft
      have htake_steps :
          n < (trace.steps.take lossPrefix.length).length := by
        simpa using hleft
      simpa [List.getElem_map, List.getElem_take,
        Nat.min_eq_left hlen] using
        hfocus ⟨n, hn_loss⟩
  · intro step hstep
    rcases List.getElem_of_mem hstep with ⟨n, hn, rfl⟩
    have hn_loss : n < lossPrefix.length := by
      simpa [Nat.min_eq_left hlen] using hn
    simpa [List.getElem_take, Nat.min_eq_left hlen] using
      hkind ⟨n, hn_loss⟩

/--
Focused initial-elimination prefixes expose their indexed focus equations.

This is the reverse direction of
`hasInitialEliminationFocusPrefix_of_getElem` for callers that prefer to keep a
single prefix predicate in theorem statements.
-/
theorem get_focus_eq_of_initialEliminationFocusPrefix
    {Candidate : Type*} {trace : STVTrace Candidate}
    {lossPrefix : List Candidate}
    (hprefix : trace.HasInitialEliminationFocusPrefix lossPrefix)
    (i : Fin lossPrefix.length) :
    (trace.steps.get ⟨i.1, Nat.lt_of_lt_of_le i.2 hprefix.1⟩).focus =
      some (lossPrefix.get i) := by
  rcases hprefix with ⟨hlen, hfocus, _hkind⟩
  have hget? :
      ((trace.steps.take lossPrefix.length).map STVStep.focus)[i.1]? =
        (lossPrefix.map some)[i.1]? := by
    rw [hfocus]
  have hsome :
      some ((trace.steps.get
          ⟨i.1, Nat.lt_of_lt_of_le i.2 hlen⟩).focus) =
        some (some (lossPrefix.get i)) := by
    simpa [List.getElem?_map, List.getElem?_eq_getElem, List.getElem_take,
      Nat.min_eq_left hlen] using hget?
  exact Option.some.inj hsome

/--
Focused initial-elimination prefixes expose their indexed elimination-kind
equations.
-/
theorem get_kind_eq_of_initialEliminationFocusPrefix
    {Candidate : Type*} {trace : STVTrace Candidate}
    {lossPrefix : List Candidate}
    (hprefix : trace.HasInitialEliminationFocusPrefix lossPrefix)
    (i : Fin lossPrefix.length) :
    (trace.steps.get ⟨i.1, Nat.lt_of_lt_of_le i.2 hprefix.1⟩).kind =
      StepKind.eliminate := by
  rcases hprefix with ⟨hlen, _hfocus, hkind⟩
  have htake_mem :
      (trace.steps.take lossPrefix.length).get
          ⟨i.1, by simpa [Nat.min_eq_left hlen] using i.2⟩ ∈
        trace.steps.take lossPrefix.length :=
    List.getElem_mem _
  simpa [List.getElem_take, Nat.min_eq_left hlen] using
    hkind _ htake_mem

/--
If the first `length` trace steps are eliminations, then the trace-derived
round-outcome sequence has `length` initial losing labels.
-/
theorem hasInitialLossPrefix_roundOutcomeSequence_of_initialEliminationPrefix
    {Candidate : Type*} {trace : STVTrace Candidate} {length : ℕ}
    (hprefix : trace.HasInitialEliminationPrefix length) :
    RoundOutcome.HasInitialLossPrefix trace.roundOutcomeSequence length := by
  rcases hprefix with ⟨hlen, hall⟩
  unfold roundOutcomeSequence
  change (trace.steps.filterMap STVStep.roundOutcome?).take length =
    List.replicate length RoundOutcome.lose
  induction length generalizing trace with
  | zero =>
      simp
  | succ length ih =>
      cases trace with
      | mk steps =>
          cases steps with
          | nil =>
              simp at hlen
          | cons step rest =>
              have hstep : step.kind = StepKind.eliminate := by
                exact hall step (by simp)
              have hlen_tail : length ≤ rest.length := by
                exact Nat.succ_le_succ_iff.mp hlen
              have hall_tail :
                  ∀ step', step' ∈ rest.take length →
                    step'.kind = StepKind.eliminate := by
                intro step' hstep'
                exact hall step' (by simp [hstep'])
              have htail :
                  (({ steps := rest } : STVTrace Candidate).steps.filterMap
                      STVStep.roundOutcome?).take length =
                    List.replicate length RoundOutcome.lose := by
                exact ih
                  (trace := ({ steps := rest } : STVTrace Candidate))
                  hlen_tail hall_tail
              rw [← Nat.succ_eq_add_one length, List.replicate_succ]
              simp [STVStep.roundOutcome?, hstep]
              exact htail

end STVTrace

/--
An STV structure consisting of a final social choice order and a list of
round-by-round win/loss labels.
-/
structure OrderSequenceStructure (Candidate : Type*) where
  finalOrder : FinalOrder Candidate
  sequence : List RoundOutcome

namespace OrderSequenceStructure

/-- The round sequence has one label for each ranked candidate. -/
def validLength {Candidate : Type*} (struct : OrderSequenceStructure Candidate) : Prop :=
  struct.sequence.length = struct.finalOrder.order.length

end OrderSequenceStructure

/--
Constraint family assigning ballot data to order-and-sequence structures.

For a fixed structure, `constraints structure data` is the region predicate
describing the data points whose STV run follows that structure.
-/
abbrev StructureConstraints (Data Struct : Type*) := Struct → Data → Prop

/--
Canonical constraints generated by a deterministic classifier: a structure is
feasible at a data point exactly when it is the classifier's selected
structure.
-/
def classifierStructureConstraints {Data Struct : Type*}
    (classify : Data → Struct) : StructureConstraints Data Struct :=
  fun struct data => struct = classify data

/-- A family of structure constraints partitions the data space. -/
def StructurePartition {Data Struct : Type*}
    (constraints : StructureConstraints Data Struct) : Prop :=
  ∀ data, ∃! struct, constraints struct data

/--
A deterministic structure classifier characterizes a constraint family when a
data point satisfies exactly the constraints of its classified structure.

For STV order/sequence proofs, this is the paper-neutral form of verifying that
a constraint-generation algorithm has replayed the same tie-broken structure as
the direct deterministic mechanism.
-/
def StructureConstraintCharacterization {Data Struct : Type*}
    (classify : Data → Struct) (constraints : StructureConstraints Data Struct) :
    Prop :=
  ∀ {data struct}, constraints struct data ↔ struct = classify data

/--
The canonical classifier-generated constraints are characterized by that
classifier.
-/
theorem structureConstraintCharacterization_classifierStructureConstraints
    {Data Struct : Type*} (classify : Data → Struct) :
    StructureConstraintCharacterization classify
      (classifierStructureConstraints classify) := by
  intro data struct
  rfl

/-- Characterized structure constraints form a partition of the data space. -/
theorem structurePartition_of_structureConstraintCharacterization
    {Data Struct : Type*} {classify : Data → Struct}
    {constraints : StructureConstraints Data Struct}
    (hcharacterization :
      StructureConstraintCharacterization classify constraints) :
    StructurePartition constraints := by
  intro data
  refine ⟨classify data, ?_, ?_⟩
  · exact (hcharacterization (data := data) (struct := classify data)).mpr rfl
  · intro struct hstruct
    exact (hcharacterization (data := data) (struct := struct)).mp hstruct

/-- The classified structure itself satisfies characterized constraints. -/
theorem classified_structure_satisfies_of_structureConstraintCharacterization
    {Data Struct : Type*} {classify : Data → Struct}
    {constraints : StructureConstraints Data Struct}
    (hcharacterization :
      StructureConstraintCharacterization classify constraints) (data : Data) :
    constraints (classify data) data := by
  exact (hcharacterization (data := data) (struct := classify data)).mpr rfl

/-- Any structure satisfying characterized constraints is the classified one. -/
theorem structure_eq_classify_of_structureConstraintCharacterization
    {Data Struct : Type*} {classify : Data → Struct}
    {constraints : StructureConstraints Data Struct}
    (hcharacterization :
      StructureConstraintCharacterization classify constraints)
    {data : Data} {struct : Struct} (hstruct : constraints struct data) :
    struct = classify data := by
  exact (hcharacterization (data := data) (struct := struct)).mp hstruct

/-- Existence of a feasible structure from a structure partition. -/
theorem exists_structure_of_structurePartition {Data Struct : Type*}
    {constraints : StructureConstraints Data Struct}
    (hpartition : StructurePartition constraints) (data : Data) :
    ∃ struct, constraints struct data := by
  rcases hpartition data with ⟨struct, hstruct, _hunique⟩
  exact ⟨struct, hstruct⟩

/-- Uniqueness of the feasible structure from a structure partition. -/
theorem structure_eq_of_structurePartition {Data Struct : Type*}
    {constraints : StructureConstraints Data Struct}
    (hpartition : StructurePartition constraints) {data : Data}
    {struct otherStruct : Struct}
    (hstruct : constraints struct data)
    (hother : constraints otherStruct data) :
    struct = otherStruct := by
  rcases hpartition data with ⟨witness, _hwitness, hunique⟩
  exact (hunique struct hstruct).trans (hunique otherStruct hother).symm

/--
Agreement between directly running an election rule and reading the outcome
encoded by a verified structure.
-/
def StructureOutcomeAgreement {Data Struct Outcome : Type*}
    (run : Data → Outcome) (readOutcome : Struct → Outcome)
    (constraints : StructureConstraints Data Struct) : Prop :=
  ∀ {data struct}, constraints struct data → run data = readOutcome struct

/--
If the direct run agrees with the deterministic structure classifier, then
characterized constraints agree with the direct run for every verified
structure.
-/
theorem structureOutcomeAgreement_of_structureConstraintCharacterization
    {Data Struct Outcome : Type*} {run : Data → Outcome}
    {readOutcome : Struct → Outcome} {classify : Data → Struct}
    {constraints : StructureConstraints Data Struct}
    (hcharacterization :
      StructureConstraintCharacterization classify constraints)
    (hrun : ∀ data, run data = readOutcome (classify data)) :
    StructureOutcomeAgreement run readOutcome constraints := by
  intro data struct hstruct
  have hstruct_eq : struct = classify data :=
    (hcharacterization (data := data) (struct := struct)).mp hstruct
  rw [hstruct_eq]
  exact hrun data

/-- Constraint verification recovers the same outcome as directly running the rule. -/
theorem run_eq_readOutcome_of_structureOutcomeAgreement {Data Struct Outcome : Type*}
    {run : Data → Outcome} {readOutcome : Struct → Outcome}
    {constraints : StructureConstraints Data Struct}
    (hagreement : StructureOutcomeAgreement run readOutcome constraints)
    {data : Data} {struct : Struct}
    (hstruct : constraints struct data) :
    run data = readOutcome struct :=
  hagreement hstruct

/--
Generic replay predicate for a proposed structure and deterministic trace.

Paper folders should refine this predicate by proving the source-specific trace
construction implies the relevant final order or winner/loser structure.
-/
def StructureReplay {Candidate : Type*}
    (trace : STVTrace Candidate) (outcome : WinLossStructure Candidate) : Prop :=
  trace.activeMonotone ∧ Disjoint outcome.winners outcome.losers

theorem structureReplay_disjoint {Candidate : Type*}
    {trace : STVTrace Candidate} {outcome : WinLossStructure Candidate}
    (h : StructureReplay trace outcome) :
    Disjoint outcome.winners outcome.losers :=
  h.2

end Voting
end SocialChoice
end EconCSLib
