import EconCSLib.Foundations.Probability.Admissions
import EconCSLib.Foundations.Probability.CTMC
import EconCSLib.Foundations.Probability.RenewalReward
import EconCSLib.Foundations.Probability.StochasticDominance
import EconCSLib.Learning.Bandits.ThompsonSampling
import GLM20DroppingStandardizedTesting
import LG21TestOptionalPolicies
import GN21DriverSurgePricing

/-!
# HumanStartHere

Open this file in VS Code with the Lean 4 extension.
This file is for humans who want a small, compiling tour of the current repo.

Read the comments from top to bottom and click or hover on identifiers to
inspect their types in the Lean Infoview.
-/

open scoped BigOperators
open EconCSLib

namespace HumanStartHere

/-!
## 1. The smallest Lean objects

- `def` creates a new object.
- `#check` asks Lean for the type of an object.
- `example` states something and proves it immediately.
-/

def myScore : ℝ := 3

def addOne (x : ℝ) : ℝ := x + 1

#check myScore
#check addOne
#check addOne myScore

example : addOne myScore = 4 := by
  norm_num [addOne, myScore]

/-!
## 2. The reusable textbook layer

The core library lives under `EconCSLib/`.  These are reusable declarations
that paper folders build on.
-/

#check EconCSLib.pmfExp
#check EconCSLib.pmfProb
#check EconCSLib.PMF.FirstOrderLe
#check EconCSLib.FiniteMDP.actionValue_le_of_firstOrderLe
#check EconCSLib.FiniteMDP.IncentiveCompatibleAtHorizon
#check EconCSLib.FiniteMDP.incentiveCompatibleAtHorizon_of_greedy_optimalValue
#check EconCSLib.FiniteMDP.not_incentiveCompatibleAtHorizon_of_profitableDeviation
#check EconCSLib.StrictQuasiConvexOnPositive
#check EconCSLib.StrictQuasiConcaveOnPositive
#check EconCSLib.strictQuasiConvexOnPositive_of_deriv_proxy_strictMono
#check EconCSLib.StrictQuasiConvexOnPositive.lt_of_between
#check EconCSLib.StrictQuasiConcaveOnPositive.lt_between
#check EconCSLib.twoStateCtmcSwitchProb
#check EconCSLib.twoStateCtmcSwitchProb_pos
#check EconCSLib.twoStateCtmcSwitchProb_lt_rate_mul_time
#check EconCSLib.twoStateCtmcSwitchProb_deriv_eq_forward
#check EconCSLib.twoStateCtmcSwitchProbPerTime_deriv_neg
#check EconCSLib.twoStateCtmcSwitchProbPerTime_lt_rate
#check EconCSLib.twoStateCtmcSwitchProbPerTime_strictAntiOn_Ioi
#check EconCSLib.twoStateCtmcSwitchProbPerTime_tendsto_at_zero
#check EconCSLib.twoStateCtmcStayProb
#check EconCSLib.twoStateCtmcStayProb_deriv_eq_forward
#check EconCSLib.twoStateCtmcTransitionProb
#check EconCSLib.twoStateCtmcTransitionProb_row_sum
#check EconCSLib.renewalRewardRate
#check EconCSLib.renewalRewardRate_le_add_component_of_le_average
#check EconCSLib.renewalRewardRate_remove_component_ge_of_average_le
#check EconCSLib.renewalRewardRate_lt_replace_reward_same_time_of_lt
#check EconCSLib.Decision.IsThompsonSampling

/-!
## 3. Admissions probability primitives

The two standardized-testing paper folders currently build on this finite
admissions abstraction.
-/

#check EconCSLib.AdmissionsModel
#check EconCSLib.TwoSignalAdmissionsModel
#check EconCSLib.ConditionalResamplingExperiment
#check EconCSLib.admissionsJointMass
#check EconCSLib.admissionsPosteriorExpectation
#check EconCSLib.admissionsSelectionProb
#check EconCSLib.admissionsSelectedWelfareMass
#check EconCSLib.admissionsSelectedWelfareConditionalExp
#check EconCSLib.admissionsSelectedWelfareMass_eq_selectionProb_mul_conditionalExp
#check EconCSLib.admissionsSelectedWelfareExp_decompose

/-!
## 4. Testing-paper entrypoints

These are paper-local audit surfaces.  They intentionally preserve paper names
and notation while calling the reusable admissions layer.
-/

#check GLM20DroppingStandardizedTesting.GLM20Model
#check GLM20DroppingStandardizedTesting.GLM20SourcePolicySurface
#check GLM20DroppingStandardizedTesting.GLM20StrategicEquilibriumData
#check GLM20DroppingStandardizedTesting.glm20StrategicEquilibrium
#check GLM20DroppingStandardizedTesting.GLM20StrategicPolicySurface
#check GLM20DroppingStandardizedTesting.glm20GroupFair
#check GLM20DroppingStandardizedTesting.glm20IndividualFair
#check GLM20DroppingStandardizedTesting.glm20BlackwellSufficient
#check GLM20DroppingStandardizedTesting.paper_lemma1_estimated_skill_of_certificate
#check GLM20DroppingStandardizedTesting.paper_proposition1_metrics_fixed_policy_of_certificate
#check GLM20DroppingStandardizedTesting.paper_lemma2_individual_fairness_gap_decreases_of_certificate
#check GLM20DroppingStandardizedTesting.paper_theorem1_dropping_tests_with_barriers_of_certificate
#check GLM20DroppingStandardizedTesting.paper_theorem2_dropping_tests_without_barriers_of_certificate
#check GLM20DroppingStandardizedTesting.paper_lemma3_unique_equilibrium_full_policy_of_certificate
#check GLM20DroppingStandardizedTesting.paper_proposition2_unique_two_school_equilibrium_of_certificate
#check GLM20DroppingStandardizedTesting.paper_proposition3_equilibrium_under_full_policy_of_certificate
#check GLM20DroppingStandardizedTesting.paper_theorem3_two_school_academic_merit_of_certificate
#check GLM20DroppingStandardizedTesting.paper_proposition5_strategic_academic_merit_of_certificate
#check GLM20DroppingStandardizedTesting.paper_proposition6_strategic_diversity_of_certificate
#check GLM20DroppingStandardizedTesting.paper_appendixD_gaussian_support_of_certificate
#check GLM20DroppingStandardizedTesting.paper_appendixF_blackwell_ssd_support_of_certificate
#check GLM20DroppingStandardizedTesting.paper_propositions7_9_generalization_affirmative_action_of_certificate
#check GLM20DroppingStandardizedTesting.glm20WithTestModel
#check GLM20DroppingStandardizedTesting.glm20WithoutTestModel
#check GLM20DroppingStandardizedTesting.glm20_with_test_exp_decompose
#check GLM20DroppingStandardizedTesting.glm20_no_test_exp_decompose

#check LG21TestOptionalPolicies.LG21Model
#check LG21TestOptionalPolicies.lg21BaseModel
#check LG21TestOptionalPolicies.lg21TestModel
#check LG21TestOptionalPolicies.LG21EquilibriumData
#check LG21TestOptionalPolicies.lg21Equilibrium
#check LG21TestOptionalPolicies.LG21SourcePolicySurface
#check LG21TestOptionalPolicies.lg21SourceLatentSkillFair
#check LG21TestOptionalPolicies.lg21SourceObservablyFair
#check LG21TestOptionalPolicies.lg21SourceDemographicallyFair
#check LG21TestOptionalPolicies.lg21SourceTestBlank
#check LG21TestOptionalPolicies.paper_interface_theorem3_1_section3_optional_reporting_strategic_withholding
#check LG21TestOptionalPolicies.paper_interface_theorem3_1_section3_report_required_strategic_withholding
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_fairness_impossibility
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_fairness_impossibility
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_no_test_relevance
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_no_test_relevance
#check LG21TestOptionalPolicies.paper_interface_definition5_observable_identity_certificate
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_event_share_binary_mixture_observable_identity_certificate
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_fairness_iff_test_blank_of_gaussian_upper_tail_event_or_blank_source_equilibrium_observable_identities
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_fairness_iff_test_blank_of_upper_tail_event_or_blank_source_equilibrium_observable_identities
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_optional_reporting_fairness_impossibility_certificate_of_gaussian_upper_tail_blank_on_zero_event_share_constant_latent_surface_posterior_payoff
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_report_required_fairness_impossibility_certificate_of_upper_tail_blank_on_zero_event_share_constant_latent_surface_unit_centered_payoff
#check LG21TestOptionalPolicies.paper_interface_theorem3_1_section3_optional_reporting_strategic_withholding_event_share_of_full_support_not_all
#check LG21TestOptionalPolicies.paper_interface_theorem3_1_section3_report_required_strategic_withholding_event_share_of_full_support_not_all
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_pmf_event_share_fn_lt_one_of_full_support_not_all
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_no_raw_relevance_on_nonzero_share_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_no_raw_relevance_on_nonzero_share_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_no_raw_relevance_on_positive_event_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_no_raw_relevance_on_positive_event_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_optional_reporting_fairness_iff_no_raw_relevance_on_nonzero_share_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_section3_report_required_fairness_iff_no_raw_relevance_on_nonzero_share_of_blank_on_zero_event_share
#check LG21TestOptionalPolicies.paper_interface_definition5_blank_on_zero_event_share_no_normalized_relevance_iff_no_raw_relevance_on_nonzero_share
#check LG21TestOptionalPolicies.paper_interface_definition5_blank_on_zero_event_share_no_normalized_relevance_iff_no_raw_relevance_on_positive_event
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_not_latent_or_observable_fair_of_concrete_optional_base_affine_binary_mixture_point_estimate_distinct_supported_tests_of_event_share_constant_latent_mapped_actor_law_of_finite_test_full_support
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_not_latent_or_observable_fair_of_concrete_optional_base_affine_binary_mixture_point_estimate_distinct_supported_tests_of_event_share_constant_latent_mapped_actor_law_of_finite_test_full_support_exists_distinct
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_not_latent_or_observable_fair_of_concrete_report_required_base_affine_binary_mixture_point_estimate_distinct_supported_tests_of_event_share_centered_baseTerm_constant_latent_mapped_actor_law_by_definition_of_full_support
#check LG21TestOptionalPolicies.paper_interface_theorem3_2_not_latent_or_observable_fair_of_concrete_report_required_base_affine_binary_mixture_point_estimate_distinct_supported_tests_of_event_share_centered_baseTerm_constant_latent_mapped_actor_law_by_definition_of_full_support_exists_distinct
#check LG21TestOptionalPolicies.paper_theorem3_1_strategic_withholding_of_certificate
#check LG21TestOptionalPolicies.paper_theorem3_2_fairness_impossibility_of_certificate
#check LG21TestOptionalPolicies.paper_lemma4_1_strategy_proofness_of_certificate
#check LG21TestOptionalPolicies.paper_proposition4_2_not_latent_skill_fair_of_certificate
#check LG21TestOptionalPolicies.paper_proposition4_3_not_observable_or_demographic_fair_of_certificate
#check LG21TestOptionalPolicies.paper_definition6_resampling_policy_observable_kernel
#check LG21TestOptionalPolicies.paper_interface_definition6_access_estimate_kernel_eq_map
#check LG21TestOptionalPolicies.paper_interface_definition6_resampling_estimate_kernel_eq_map
#check LG21TestOptionalPolicies.paper_theorem4_4_resampling_policy_observably_fair
#check LG21TestOptionalPolicies.paper_theorem4_4_resampling_policy_demographically_fair
#check LG21TestOptionalPolicies.paper_interface_theorem4_4_resampling_policy_source_strategy_proof_observable_and_demographic_fair
#check LG21TestOptionalPolicies.lg21_base_exp_decompose
#check LG21TestOptionalPolicies.lg21_test_exp_decompose

/-!
## 5. Driver-surge entrypoints

The driver-surge paper is continuous-time in the source.  Its current Lean
surface exposes source-facing continuous predicates and finite MDP support
lemmas without treating the finite layer as a source theorem substitute.
-/

#check GN21DriverSurgePricing.PaperInterface.review_definition_single_state_ic
#check GN21DriverSurgePricing.PaperInterface.review_definition_dynamic_ic
#check GN21DriverSurgePricing.PaperInterface.review_definition_threshold_policy
#check GN21DriverSurgePricing.PaperInterface.review_definition_dynamic_defined_reward
#check GN21DriverSurgePricing.PaperInterface.review_section2_single_state_renewal_reward_iid_bridge
#check GN21DriverSurgePricing.PaperInterface.review_proposition3_1_affine_single_state_ic
#check GN21DriverSurgePricing.PaperInterface.review_theorem1_single_state_threshold_best_response
#check GN21DriverSurgePricing.PaperInterface.review_lemma1_measured_dynamic_reward_decomposition
#check GN21DriverSurgePricing.PaperInterface.review_lemma2_switch_probability_formula
#check GN21DriverSurgePricing.PaperInterface.review_lemma3_measured_time_fraction_formula
#check GN21DriverSurgePricing.PaperInterface.review_lemma4_single_state_threshold_uniqueness
#check GN21DriverSurgePricing.PaperInterface.review_lemma5_fixed_response_policy_form
#check GN21DriverSurgePricing.PaperInterface.review_lemma6_upper_endpoint_derivative_formula
#check GN21DriverSurgePricing.PaperInterface.review_lemma7_affine_positive_additive_response_quasi_convex
#check GN21DriverSurgePricing.PaperInterface.review_lemma8_affine_negative_additive_response_quasi_concave
#check GN21DriverSurgePricing.PaperInterface.review_lemma9_surge_derivative_positive_of_acceptAll_bounds
#check GN21DriverSurgePricing.PaperInterface.review_lemma10_nonsurge_derivative_positive_of_acceptAll_bounds
#check GN21DriverSurgePricing.PaperInterface.review_remark1_switch_probability_per_time_strictAntiOn
#check GN21DriverSurgePricing.PaperInterface.review_remark3_switch_probability_per_time_tendsto_at_zero
#check GN21DriverSurgePricing.PaperInterface.review_remark4_switch_time_minus_switch_probability_nonneg
#check GN21DriverSurgePricing.PaperInterface.review_theorem2_multiplicative_policy_shape_ae
#check GN21DriverSurgePricing.PaperInterface.review_theorem2_multiplicative_positive_finite_cutoff_not_ic_both_states
#check GN21DriverSurgePricing.PaperInterface.review_theorem4_structural_policy_representatives
#check GN21DriverSurgePricing.PaperInterface.review_theorem3_feasible_sequential_current_bounds_source_data_statement

#check GN21DriverSurgePricing.singleStateIncentiveCompatible
#check GN21DriverSurgePricing.dynamicIncentiveCompatible
#check GN21DriverSurgePricing.dynamicStateReward
#check GN21DriverSurgePricing.dynamicStateReward_optimal_of_dynamicOptimal
#check GN21DriverSurgePricing.dynamicOptimal_acceptAll_of_statewise_acceptAll_improvements
#check GN21DriverSurgePricing.eq_acceptAllPolicy_of_subset_acceptAll_of_acceptsAll
#check GN21DriverSurgePricing.eq_acceptAllDynamicPolicy_of_statewise_subset_acceptsAll
#check GN21DriverSurgePricing.acceptAllDynamic_unique_optimal_of_strict_dominates
#check GN21DriverSurgePricing.acceptAllDynamic_unique_optimal_of_statewise_accept_all_optima
#check GN21DriverSurgePricing.gn21SwitchProb
#check GN21DriverSurgePricing.singleStateTripMass_nonneg
#check GN21DriverSurgePricing.singleStateTripTime_nonneg_of_subset_acceptAll
#check GN21DriverSurgePricing.singleStateTripTime_le_acceptAll_of_subset
#check GN21DriverSurgePricing.singleStateTripMass_eq_zero_of_time_zero_subset_acceptAll
#check GN21DriverSurgePricing.strictThresholdPolicy
#check GN21DriverSurgePricing.completeThresholdPolicy
#check GN21DriverSurgePricing.thresholdBoundaryPolicy
#check GN21DriverSurgePricing.strictThresholdRatePolicy_strictThresholdPolicy
#check GN21DriverSurgePricing.thresholdRatePolicy_completeThresholdPolicy
#check GN21DriverSurgePricing.partialThresholdRatePolicy_strictThresholdPolicy
#check GN21DriverSurgePricing.partialThresholdRatePolicy_completeThresholdPolicy
#check GN21DriverSurgePricing.measurableSet_strictThresholdPolicy
#check GN21DriverSurgePricing.measurableSet_completeThresholdPolicy
#check GN21DriverSurgePricing.measurableSet_thresholdBoundaryPolicy
#check GN21DriverSurgePricing.onTripRateEquals_thresholdBoundaryPolicy
#check GN21DriverSurgePricing.paper_theorem1_add_positive_time_set_if_average_above_current
#check GN21DriverSurgePricing.paper_theorem1_remove_positive_time_set_if_average_below_current
#check GN21DriverSurgePricing.paper_theorem1_step1_same_time_more_payment_improves_reward
#check GN21DriverSurgePricing.paper_theorem1_step1_equal_utilization_swap_improves_reward
#check GN21DriverSurgePricing.paper_theorem1_add_positive_time_set_if_pointwise_rate_above_current
#check GN21DriverSurgePricing.paper_theorem1_remove_positive_time_set_if_pointwise_rate_below_current
#check GN21DriverSurgePricing.paper_theorem1_step2_add_boundary_set_if_threshold_ge_current
#check GN21DriverSurgePricing.paper_theorem1_step2_remove_boundary_set_if_threshold_le_current
#check GN21DriverSurgePricing.paper_theorem1_complete_threshold_optimal_of_step_certificates
#check GN21DriverSurgePricing.paper_theorem1_threshold_certificate_of_step_certificates
#check GN21DriverSurgePricing.paper_lemma4_single_state_unique_threshold_of_certificate
#check GN21DriverSurgePricing.measurable_affinePricing_rate
#check GN21DriverSurgePricing.measurableSet_strictThresholdPolicy_affinePricing
#check GN21DriverSurgePricing.measurableSet_completeThresholdPolicy_affinePricing
#check GN21DriverSurgePricing.measurableSet_thresholdBoundaryPolicy_affinePricing
#check GN21DriverSurgePricing.paper_lemma1_state_reward_rate_algebra
#check GN21DriverSurgePricing.paper_lemma1_measured_state_reward_rate_algebra
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_decomposition
#check GN21DriverSurgePricing.gn21MeasuredStateRewardRate_eq_scaled_primitives
#check GN21DriverSurgePricing.gn21MeasuredTimeFraction_eq_scaled_primitives
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_eq_aggregate_scaled_primitives
#check GN21DriverSurgePricing.gn21MeasuredAggregateRewardPrimitives
#check GN21DriverSurgePricing.GN21MeasuredPairNondegenerate
#check GN21DriverSurgePricing.gn21MeasuredPairNondegenerate_of_positive_primitives
#check GN21DriverSurgePricing.gn21MeasuredPairNondegenerate_of_positive_measure
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_eq_aggregate_primitives
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_eq_aggregate_primitives_of_nondegenerate
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_le_of_aggregate_primitives_le
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_lt_of_aggregate_primitives_lt
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_le_of_aggregate_pair_le_of_nondegenerate
#check GN21DriverSurgePricing.paper_lemma1_measured_dynamic_reward_lt_of_aggregate_pair_lt_of_nondegenerate
#check GN21DriverSurgePricing.gn21MeasuredDynamicRewardFunctional
#check GN21DriverSurgePricing.gn21MeasuredDynamicRewardFunctional_apply
#check GN21DriverSurgePricing.gn21MeasuredCTMCStructuredDynamicReward
#check GN21DriverSurgePricing.gn21AcceptAllScaledStateTime
#check GN21DriverSurgePricing.gn21AcceptAllExitWeightIntegral
#check GN21DriverSurgePricing.dynamicStateReward_gn21MeasuredDynamicRewardFunctional_zero
#check GN21DriverSurgePricing.dynamicStateReward_gn21MeasuredDynamicRewardFunctional_one
#check GN21DriverSurgePricing.gn21ExitWeightIntegral_ge_switch_of_nonneg
#check GN21DriverSurgePricing.gn21ExitWeightIntegral_pos_of_switch_pos
#check GN21DriverSurgePricing.gn21ScaledStateTime_ge_one_of_nonneg
#check GN21DriverSurgePricing.gn21ScaledStateTime_pos_of_nonneg
#check GN21DriverSurgePricing.ctmcDynamicSwitchProb
#check GN21DriverSurgePricing.ctmcStructuredDynamicSurgePrice
#check GN21DriverSurgePricing.ctmcStructuredDynamicSurgePrice_price_form
#check GN21DriverSurgePricing.ctmcDynamicSwitchProb_zero
#check GN21DriverSurgePricing.ctmcDynamicSwitchProb_one
#check GN21DriverSurgePricing.paper_lemma2_switch_probability_forward_equation
#check GN21DriverSurgePricing.paper_lemma2_switch_probability_pos
#check GN21DriverSurgePricing.paper_lemma2_transition_probability_zero_time
#check GN21DriverSurgePricing.paper_lemma2_transition_probability_row_sum
#check GN21DriverSurgePricing.paper_remark2_structured_scaled_earning_algebra
#check GN21DriverSurgePricing.gn21StructuredDerivativeSwitchBracket
#check GN21DriverSurgePricing.gn21StructuredDerivativeStaticTerm
#check GN21DriverSurgePricing.gn21StructuredDerivativeSignKernel_eq_bracket_static
#check GN21DriverSurgePricing.structuredDerivativeKernel_pos_of_linearization_bound
#check GN21DriverSurgePricing.paper_remark2_structured_derivative_kernel_pos_of_ctmc_switch
#check GN21DriverSurgePricing.structuredDerivativeKernel_pos_of_linearization_bound_and_tail
#check GN21DriverSurgePricing.paper_remark2_structured_derivative_kernel_pos_of_ctmc_switch_and_tail
#check GN21DriverSurgePricing.paper_remark2_structured_derivative_kernel_algebra
#check GN21DriverSurgePricing.paper_remark1_switch_probability_per_time_deriv_neg
#check GN21DriverSurgePricing.paper_remark1_switch_probability_per_time_strictAntiOn
#check GN21DriverSurgePricing.paper_remark3_switch_probability_deriv_at_zero
#check GN21DriverSurgePricing.paper_remark3_switch_probability_per_time_tendsto_at_zero
#check GN21DriverSurgePricing.paper_remark4_switch_time_minus_switch_probability_nonneg
#check GN21DriverSurgePricing.paper_remark4_switch_probability_lt_rate_mul_time
#check GN21DriverSurgePricing.paper_remark4_switch_probability_per_time_lt_rate
#check GN21DriverSurgePricing.paper_remark4_switch_time_minus_switch_probability_pos
#check GN21DriverSurgePricing.paper_remark4_switch_time_minus_switch_probability_deriv_nonneg
#check GN21DriverSurgePricing.paper_remark4_switch_time_minus_switch_probability_deriv_pos
#check GN21DriverSurgePricing.paper_remark4_switch_time_minus_switch_probability_strictMonoOn
#check GN21DriverSurgePricing.paper_remark4_scaled_time_minus_exit_weight_eq_integral
#check GN21DriverSurgePricing.paper_remark4_scaled_time_minus_exit_weight_integral_pos_of_positive_measure
#check GN21DriverSurgePricing.paper_remark4_scaled_time_minus_exit_weight_pos_of_positive_measure
#check GN21DriverSurgePricing.paper_remark4_scaled_time_minus_exit_weight_le_acceptAll
#check GN21DriverSurgePricing.paper_remark4_exit_weight_integral_component_pos_of_positive_measure
#check GN21DriverSurgePricing.paper_remark4_exit_weight_gt_switch_of_positive_measure
#check GN21DriverSurgePricing.paper_remark4_exit_weight_integral_component_le_acceptAll
#check GN21DriverSurgePricing.paper_lemma3_time_fraction_formula_algebra
#check GN21DriverSurgePricing.paper_lemma3_measured_time_fraction_formula_algebra
#check GN21DriverSurgePricing.paper_lemma3_measured_time_fractions_sum_to_one
#check GN21DriverSurgePricing.paper_lemma5_optimizer_replacement_of_certificate
#check GN21DriverSurgePricing.rejectLongTripsPolicy
#check GN21DriverSurgePricing.rejectShortTripsPolicy
#check GN21DriverSurgePricing.acceptMiddleTripsPolicy
#check GN21DriverSurgePricing.rejectMiddleTripsPolicy
#check GN21DriverSurgePricing.measurableSet_rejectLongTripsPolicy
#check GN21DriverSurgePricing.measurableSet_rejectShortTripsPolicy
#check GN21DriverSurgePricing.measurableSet_acceptMiddleTripsPolicy
#check GN21DriverSurgePricing.measurableSet_rejectMiddleTripsPolicy
#check GN21DriverSurgePricing.lemma5PolicyForm_positive_acceptAllPolicy
#check GN21DriverSurgePricing.lemma5PolicyForm_strictlyIncreasing_rejectShortTripsPolicy
#check GN21DriverSurgePricing.lemma5PolicyForm_strictlyDecreasing_rejectLongTripsPolicy
#check GN21DriverSurgePricing.lemma5PolicyForm_strictlyQuasiConvex_rejectMiddleTripsPolicy
#check GN21DriverSurgePricing.lemma5PolicyForm_strictlyQuasiConcave_acceptMiddleTripsPolicy
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_strictlyQuasiConvex_of_lemma7_affine_ctmc_response
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_strictlyQuasiConcave_of_lemma8_affine_ctmc_response
#check GN21DriverSurgePricing.paper_lemma5_strictQuasiConvex_response_lt_of_between
#check GN21DriverSurgePricing.paper_lemma5_strictQuasiConcave_response_lt_between
#check GN21DriverSurgePricing.lemma5PositiveOptimizerReplacementCertificate_acceptAll
#check GN21DriverSurgePricing.lemma5PolicyForm_of_optimizer_replacement_certificate_of_optimal
#check GN21DriverSurgePricing.acceptsAllTrips_of_positive_optimizer_replacement_certificate_of_optimal
#check GN21DriverSurgePricing.sameStrictSign_trans
#check GN21DriverSurgePricing.sameStrictSign_pos_left
#check GN21DriverSurgePricing.sameStrictSign_neg_left
#check GN21DriverSurgePricing.exists_pos_between_of_lt_of_pos
#check GN21DriverSurgePricing.gn21AggregateDynamicReward
#check GN21DriverSurgePricing.gn21AggregateDynamicReward_swap
#check GN21DriverSurgePricing.gn21EndpointQiPath
#check GN21DriverSurgePricing.gn21EndpointWiPath
#check GN21DriverSurgePricing.gn21EndpointTiPath
#check GN21DriverSurgePricing.gn21LowerEndpointQiPath
#check GN21DriverSurgePricing.gn21LowerEndpointWiPath
#check GN21DriverSurgePricing.gn21LowerEndpointTiPath
#check GN21DriverSurgePricing.gn21EndpointQiPath_hasDerivAt
#check GN21DriverSurgePricing.gn21EndpointWiPath_hasDerivAt
#check GN21DriverSurgePricing.gn21EndpointTiPath_hasDerivAt
#check GN21DriverSurgePricing.gn21LowerEndpointQiPath_hasDerivAt
#check GN21DriverSurgePricing.gn21LowerEndpointWiPath_hasDerivAt
#check GN21DriverSurgePricing.gn21LowerEndpointTiPath_hasDerivAt
#check GN21DriverSurgePricing.paper_lemma6_aggregate_reward_hasDerivAt
#check GN21DriverSurgePricing.Lemma6EndpointDerivativeData
#check GN21DriverSurgePricing.lemma6DerivativeFormulaCertificate_of_endpoint_data
#check GN21DriverSurgePricing.paper_lemma6_endpoint_hasDerivAt_of_data
#check GN21DriverSurgePricing.exists_pos_right_improvement_of_hasDerivAt_pos
#check GN21DriverSurgePricing.exists_pos_right_decrease_of_hasDerivAt_neg
#check GN21DriverSurgePricing.lemma6EndpointDerivativeData_of_aggregate_paths
#check GN21DriverSurgePricing.paper_lemma6_derivative_formula_of_aggregate_paths
#check GN21DriverSurgePricing.paper_lemma6_lower_aggregate_reward_hasDerivAt
#check GN21DriverSurgePricing.paper_lemma6_lower_derivative_formula_of_aggregate_paths
#check GN21DriverSurgePricing.lemma6EndpointDerivativeData_of_interval_density_paths
#check GN21DriverSurgePricing.paper_lemma6_derivative_formula_of_interval_density_paths
#check GN21DriverSurgePricing.paper_lemma6_lower_derivative_formula_of_interval_density_paths
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_pos_of_kernel_pos_of_endpoint_data
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_neg_of_kernel_neg_of_endpoint_data
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_improvement_of_kernel_pos_of_endpoint_data
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_decrease_of_kernel_neg_of_endpoint_data
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_improvement_of_interval_density_kernel_pos
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_decrease_of_interval_density_kernel_neg
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_improvement_of_lower_interval_density_kernel_neg
#check GN21DriverSurgePricing.paper_lemma6_exists_pos_right_decrease_of_lower_interval_density_kernel_pos
#check GN21DriverSurgePricing.paper_lemma6_derivative_formula_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_pos_of_kernel_pos_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_neg_of_kernel_neg_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_same_sign_structured_kernel_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_pos_of_structured_kernel_pos_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_neg_of_structured_kernel_neg_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_kernel_eq_scaled_response
#check GN21DriverSurgePricing.paper_lemma6_derivative_kernel_same_sign_response
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_same_sign_response_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_pos_of_response_pos_of_certificate
#check GN21DriverSurgePricing.paper_lemma6_derivative_value_neg_of_response_neg_of_certificate
#check GN21DriverSurgePricing.paper_lemma7_8_affine_response_canonical_form
#check GN21DriverSurgePricing.paper_lemma7_canonical_response_hasDerivAt
#check GN21DriverSurgePricing.paper_lemma7_canonical_derivative_numerator_hasDerivAt
#check GN21DriverSurgePricing.paper_lemma7_canonical_derivative_numerator_deriv_pos
#check GN21DriverSurgePricing.paper_lemma7_canonical_positive_over_u_quasi_convex
#check GN21DriverSurgePricing.paper_lemma8_canonical_negative_over_u_quasi_concave
#check GN21DriverSurgePricing.paper_lemma7_canonical_ctmc_response_quasi_convex
#check GN21DriverSurgePricing.paper_lemma8_canonical_ctmc_response_quasi_concave
#check GN21DriverSurgePricing.paper_lemma7_affine_ctmc_response_eq_canonical
#check GN21DriverSurgePricing.paper_lemma8_affine_ctmc_response_eq_canonical
#check GN21DriverSurgePricing.paper_lemma7_affine_ctmc_response_quasi_convex
#check GN21DriverSurgePricing.paper_lemma8_affine_ctmc_response_quasi_concave
#check GN21DriverSurgePricing.paper_lemma7_affine_positive_additive_quasi_convex_of_certificate
#check GN21DriverSurgePricing.paper_lemma8_affine_negative_additive_quasi_concave_of_certificate
#check GN21DriverSurgePricing.paper_lemma7_affine_ctmc_quasi_convex_certificate
#check GN21DriverSurgePricing.paper_lemma8_affine_ctmc_quasi_concave_certificate
#check GN21DriverSurgePricing.lemma9StructuredLowerNumerator
#check GN21DriverSurgePricing.lemma9StructuredLowerDenominator
#check GN21DriverSurgePricing.lemma9StructuredUpperNumerator
#check GN21DriverSurgePricing.lemma9StructuredUpperDenominator
#check GN21DriverSurgePricing.lemma9StructuredLowerFromGap
#check GN21DriverSurgePricing.lemma9StructuredUpperFromExitWeight
#check GN21DriverSurgePricing.lemma9StructuredLowerFromGap_mono
#check GN21DriverSurgePricing.lemma9StructuredUpperFromExitWeight_antitone
#check GN21DriverSurgePricing.lemma9StructuredBounds_of_acceptAll_tightening
#check GN21DriverSurgePricing.lemma9StructuredStaticTerm_pos_of_upper_bound
#check GN21DriverSurgePricing.lemma9StructuredLinearEndpoint_pos_of_lower_bound
#check GN21DriverSurgePricing.paper_lemma9_structured_derivative_kernel_pos_of_current_bounds
#check GN21DriverSurgePricing.paper_lemma9_derivative_value_pos_of_current_bounds_certificate
#check GN21DriverSurgePricing.paper_lemma9_exists_pos_right_improvement_of_current_bounds_endpoint_data
#check GN21DriverSurgePricing.paper_lemma9_exists_pos_right_improvement_of_interval_density_current_bounds
#check GN21DriverSurgePricing.paper_lemma9_structured_bounds_feasible_of_lower_lt_upper
#check GN21DriverSurgePricing.lemma9StructuredUpper_pos
#check GN21DriverSurgePricing.paper_lemma9_structured_bounds_feasible_positive_of_lower_lt_upper
#check GN21DriverSurgePricing.paper_lemma9_structured_bounds_feasible_of_cross_mul
#check GN21DriverSurgePricing.paper_lemma9_structured_bounds_feasible_of_final_signs
#check GN21DriverSurgePricing.paper_lemma9_structured_bounds_feasible_positive_of_final_signs
#check GN21DriverSurgePricing.lemma9SurgeDerivativeCertificate_of_current_bounds
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_positive_of_lemma9_certificate
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_positive_of_lemma9_current_bounds
#check GN21DriverSurgePricing.paper_lemma9_surge_derivative_positive_of_certificate
#check GN21DriverSurgePricing.paper_lemma10_structured_bounds_feasible_of_positive_terms
#check GN21DriverSurgePricing.lemma10StructuredLowerNumerator
#check GN21DriverSurgePricing.lemma10StructuredLowerDenominator
#check GN21DriverSurgePricing.lemma10StructuredUpperDenominator
#check GN21DriverSurgePricing.lemma10StructuredLowerFromGap
#check GN21DriverSurgePricing.lemma10StructuredUpperFromExitWeight
#check GN21DriverSurgePricing.lemma10StructuredLowerFromGap_mono
#check GN21DriverSurgePricing.lemma10StructuredUpperFromExitWeight_antitone
#check GN21DriverSurgePricing.lemma10StructuredBounds_of_acceptAll_tightening
#check GN21DriverSurgePricing.lemma10StructuredStaticTerm_pos_of_upper_bound
#check GN21DriverSurgePricing.lemma10StructuredLinearEndpoint_pos_of_lower_bound
#check GN21DriverSurgePricing.paper_lemma10_structured_derivative_kernel_pos_of_current_bounds
#check GN21DriverSurgePricing.paper_lemma10_derivative_value_pos_of_current_bounds_certificate
#check GN21DriverSurgePricing.paper_lemma10_exists_pos_right_improvement_of_current_bounds_endpoint_data
#check GN21DriverSurgePricing.paper_lemma10_exists_pos_right_improvement_of_interval_density_current_bounds
#check GN21DriverSurgePricing.paper_lemma10_structured_bounds_feasible_of_positive_pieces
#check GN21DriverSurgePricing.lemma10NonsurgeDerivativeCertificate_of_current_bounds
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_positive_of_lemma10_certificate
#check GN21DriverSurgePricing.lemma5DerivativeShapeWitness_positive_of_lemma10_current_bounds
#check GN21DriverSurgePricing.paper_lemma10_nonsurge_derivative_positive_of_certificate
#check GN21DriverSurgePricing.theorem4NonsurgeAllowedLemma5Shape
#check GN21DriverSurgePricing.theorem4SurgeAllowedLemma5Shape
#check GN21DriverSurgePricing.theorem4NonsurgeAllowedLemma5Shape_strictlyDecreasing
#check GN21DriverSurgePricing.theorem4NonsurgeAllowedLemma5Shape_strictlyQuasiConcave
#check GN21DriverSurgePricing.theorem4SurgeAllowedLemma5Shape_strictlyIncreasing
#check GN21DriverSurgePricing.theorem4SurgeAllowedLemma5Shape_strictlyQuasiConvex
#check GN21DriverSurgePricing.theorem4NonsurgeShape_of_allowed_lemma5_form
#check GN21DriverSurgePricing.theorem4SurgeShape_of_allowed_lemma5_form
#check GN21DriverSurgePricing.theorem4NonsurgeShape_of_lemma5_positive
#check GN21DriverSurgePricing.theorem4NonsurgeShape_of_lemma5_strictlyDecreasing
#check GN21DriverSurgePricing.theorem4NonsurgeShape_of_lemma5_strictlyQuasiConcave
#check GN21DriverSurgePricing.theorem4SurgeShape_of_lemma5_positive
#check GN21DriverSurgePricing.theorem4SurgeShape_of_lemma5_strictlyIncreasing
#check GN21DriverSurgePricing.theorem4SurgeShape_of_lemma5_strictlyQuasiConvex
#check GN21DriverSurgePricing.theorem4NonsurgeShape_rejectLongTripsPolicy
#check GN21DriverSurgePricing.theorem4NonsurgeShape_acceptMiddleTripsPolicy
#check GN21DriverSurgePricing.theorem4SurgeShape_rejectShortTripsPolicy
#check GN21DriverSurgePricing.theorem4SurgeShape_rejectMiddleTripsPolicy
#check GN21DriverSurgePricing.Theorem4ShapeDerivationCertificate
#check GN21DriverSurgePricing.theorem4StructuralPolicyCertificate_of_shape_derivation
#check GN21DriverSurgePricing.paper_theorem4_dynamic_structural_policy_of_shape_derivation
#check GN21DriverSurgePricing.PaperInterface.theorem4_structural_policy_forms_of_allowed_policy_forms
#check GN21DriverSurgePricing.PaperInterface.theorem4_structural_policy_representatives_of_feasible_ae_policy_forms
#check GN21DriverSurgePricing.PaperInterface.theorem4_structural_policy_representatives_of_fixed_response_policy_forms
#check GN21DriverSurgePricing.PaperInterface.theorem4_structural_policy_representatives_of_gn21_bracket_source_data
#check GN21DriverSurgePricing.PaperInterface.theorem4_acceptAll_structural_representatives_of_positive_response_candidates
#check GN21DriverSurgePricing.PaperInterface.theorem2_one_threshold_policy_shape_ae_of_gn21_bracket_source_data
#check GN21DriverSurgePricing.Theorem4AcceptAllDerivationCertificate
#check GN21DriverSurgePricing.theorem4ShapeDerivationCertificate_of_accept_all_derivation
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_positive_lemma5_forms
#check GN21DriverSurgePricing.paper_theorem4_dynamic_structural_policy_of_accept_all_derivation
#check GN21DriverSurgePricing.Theorem4PositiveReplacementDerivationCertificate
#check GN21DriverSurgePricing.Theorem4StatewiseAcceptAllRewardCertificate
#check GN21DriverSurgePricing.Theorem4GlobalStatewiseAcceptAllRewardCertificate
#check GN21DriverSurgePricing.Theorem4StrictLocalImprovementCertificate
#check GN21DriverSurgePricing.acceptAllDynamic_unique_optimal_of_strict_local_improvements
#check GN21DriverSurgePricing.theorem4PositiveReplacementDerivationCertificate_of_statewise_accept_all_reward
#check GN21DriverSurgePricing.theorem4StatewiseAcceptAllRewardCertificate_of_global_statewise_accept_all_reward
#check GN21DriverSurgePricing.theorem4AcceptAllDerivationCertificate_of_positive_replacement
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_positive_replacement
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_global_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_strict_local_improvements
#check GN21DriverSurgePricing.theorem4GlobalStatewiseAcceptAllRewardCertificate_of_measured_reward_improvements
#check GN21DriverSurgePricing.Theorem4MeasuredAggregateAcceptAllRewardCertificate
#check GN21DriverSurgePricing.theorem4GlobalStatewiseAcceptAllRewardCertificate_of_measured_aggregate_improvements
#check GN21DriverSurgePricing.Theorem4MeasuredAggregateStrictLocalImprovementCertificate
#check GN21DriverSurgePricing.theorem4StrictLocalImprovementCertificate_of_measured_aggregate_strict_improvements
#check GN21DriverSurgePricing.paper_theorem4_accept_all_unique_optimal_of_measured_aggregate_strict_local_improvements
#check GN21DriverSurgePricing.replaceDynamicPolicyState
#check GN21DriverSurgePricing.gn21MeasuredAggregateDynamicStateReward
#check GN21DriverSurgePricing.gn21MeasuredAggregateDynamicStateReward_zero
#check GN21DriverSurgePricing.gn21MeasuredAggregateDynamicStateReward_one
#check GN21DriverSurgePricing.paper_theorem4_surge_statewise_strict_aggregate_improvement_of_lemma9_interval_density
#check GN21DriverSurgePricing.Theorem4MeasuredAggregateStatewiseStrictLocalImprovementCertificate
#check GN21DriverSurgePricing.theorem4MeasuredAggregateStrictLocalImprovementCertificate_of_statewise_strict_improvements
#check GN21DriverSurgePricing.paper_theorem4_dynamic_structural_policy_of_certificate
#check GN21DriverSurgePricing.paper_proposition3_1_affine_accept_all_ge_complement_reward_of_rejected_set
#check GN21DriverSurgePricing.paper_proposition3_1_affine_accept_all_ge_rejecting_measurable_set
#check GN21DriverSurgePricing.singleStateTripMeasureAssumptions_of_standard
#check GN21DriverSurgePricing.paper_proposition3_1_affine_single_state_measurable_ic
#check GN21DriverSurgePricing.paper_proposition3_1_affine_single_state_measurable_ic_of_standard_measure
#check GN21DriverSurgePricing.paper_theorem3_structured_price_uses_lemma2_switch_probability
#check GN21DriverSurgePricing.paper_theorem3_structured_price_closed_form
#check GN21DriverSurgePricing.theorem3FeasibilityThresholdC
#check GN21DriverSurgePricing.paper_theorem3_switch_term_nonneg
#check GN21DriverSurgePricing.paper_theorem3_feasibility_numerator_pos_of_positive_pieces
#check GN21DriverSurgePricing.paper_theorem3_feasibility_denominator_pos_of_positive_pieces
#check GN21DriverSurgePricing.paper_theorem3_scaled_denominator_pos_of_positive_pieces
#check GN21DriverSurgePricing.paper_theorem3_feasibility_thresholdC_mem_Ico
#check GN21DriverSurgePricing.paper_theorem3_feasibility_thresholdC_mem_Ico_of_positive_pieces
#check GN21DriverSurgePricing.paper_theorem3_feasibility_numerator_le_scaled_den_of_nonneg_pieces
#check GN21DriverSurgePricing.theorem3NonsurgeZRatio
#check GN21DriverSurgePricing.theorem3NonsurgeZRatio_accounting
#check GN21DriverSurgePricing.lemma10StructuredBounds_of_theorem3_ratio
#check GN21DriverSurgePricing.theorem3NonsurgeParameters_of_theorem3_ratio
#check GN21DriverSurgePricing.theorem3SurgeMultiplierFromRatio
#check GN21DriverSurgePricing.theorem3SurgeZFromRatio
#check GN21DriverSurgePricing.theorem3SurgeRatio_accounting
#check GN21DriverSurgePricing.theorem3SurgeRatio_denominator_pos
#check GN21DriverSurgePricing.theorem3SurgeMultiplierFromRatio_gt_R1
#check GN21DriverSurgePricing.theorem3SurgeZFromRatio_pos
#check GN21DriverSurgePricing.theorem3SurgeParameters_exist_of_lemma9_final_signs
#check GN21DriverSurgePricing.theorem3StructuredParameters_exist_of_ratio_and_lemma9_final_signs
#check GN21DriverSurgePricing.paper_theorem3_feasibility_thresholdC_mem_Ico_acceptAll_of_measured_primitives
#check GN21DriverSurgePricing.paper_theorem3_feasibility_thresholdC_mem_Ico_acceptAll_of_measured_primitives_closed
#check GN21DriverSurgePricing.lemma10StructuredBounds_acceptAll_of_theorem3_ratio_measured
#check GN21DriverSurgePricing.theorem3_acceptAll_measured_primitives_scalar_conditions
#check GN21DriverSurgePricing.paper_theorem1_single_state_threshold_best_response_of_certificate
#check GN21DriverSurgePricing.paper_theorem2_multiplicative_not_ic_of_witness
#check GN21DriverSurgePricing.paper_theorem3_structured_prices_ic_of_certificate
#check GN21DriverSurgePricing.structuredPricingICCertificate_of_ctmc_structured_prices
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_ic_of_accept_all_unique_optimal
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_ic_of_statewise_accept_all_optima
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_ic_of_theorem4_accept_all_derivation
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_ic_of_positive_replacement_derivation
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_ic_of_strict_local_improvements
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_exist_and_ic_of_ratio_and_positive_replacement
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_exist_and_ic_of_ratio_and_strict_local_improvements
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_exist_and_ic_of_ratio_and_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem3_ctmc_structured_prices_exist_and_ic_of_ratio_and_global_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem3_measured_ctmc_structured_prices_exist_and_ic_of_ratio_and_global_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem3_measured_ctmc_structured_prices_exist_and_ic_of_ratio_and_measured_aggregate_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem3_measured_ctmc_structured_prices_exist_and_ic_of_ratio_and_measured_aggregate_strict_local_improvements
#check GN21DriverSurgePricing.paper_theorem3_measured_ctmc_structured_prices_exist_and_ic_of_acceptAll_primitives_and_global_statewise_accept_all_reward
#check GN21DriverSurgePricing.paper_theorem3_measured_ctmc_structured_prices_exist_and_ic_of_acceptAll_primitives_and_measured_aggregate_strict_local_improvements
#check GN21DriverSurgePricing.paper_theorem3_measured_structured_positive_mass_measurable_ic_ae_unique_prices_of_source_assumptions
#check GN21DriverSurgePricing.paper_theorem3_measured_structured_positive_mass_measurable_ic_ae_unique_prices_of_source_assumptions_and_positive_response_marginal
#check GN21DriverSurgePricing.PaperInterface.theorem3_positive_response
#check GN21DriverSurgePricing.PaperInterface.theorem3_positive_fixed_response_normalized
#check GN21DriverSurgePricing.PaperInterface.theorem3_positive_mass_source
#check GN21DriverSurgePricing.PaperInterface.theorem3_feasible_sequential_current_bounds_source_data
#check GN21DriverSurgePricing.PaperInterface.theorem3_source_with_zero_mass_dominance
#check GN21DriverSurgePricing.PaperInterface.theorem3_positive_mass_source_positive_response
#check GN21DriverSurgePricing.PostPaperAudit.audit_theorem3_positive_response_source
#check GN21DriverSurgePricing.PostPaperAudit.audit_theorem3_positive_fixed_response_source
#check GN21DriverSurgePricing.PostPaperAudit.audit_theorem3_feasible_sequential_current_bounds_source_data
#check GN21DriverSurgePricing.paper_aux_finite_dynamic_pricing_ic_of_greedy
#check GN21DriverSurgePricing.paper_aux_finite_dynamic_pricing_not_ic_of_profitable_deviation

/-!
## 6. Where to read next

Start from these files:

- `README.md` for the paper status table.
- `docs/ECONCSLIB_DOMAIN_INDEX.md` for domain entrypoints.
- `EconCSLib/Foundations/Probability/Admissions.lean` for the shared
  admissions model.
- `EconCSLib/Foundations/Probability/CTMC.lean` for two-state continuous-time
  Markov chain support.
- `EconCSLib/Foundations/Probability/MDP.lean` for finite dynamic-policy
  support.
- `papers/GLM20DroppingStandardizedTesting/MainTheorems.lean`.
- `papers/LG21TestOptionalPolicies/MainTheorems.lean`.
- `papers/GN21DriverSurgePricing/MainTheorems.lean`.
-/

end HumanStartHere
