name = "EconCSLib"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["EconCSLib"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.unnecessarySimpa = false
weak.linter.unusedDecidableInType = false
weak.linter.unusedFintypeInType = false
weak.linter.unusedSectionVars = false
weak.linter.unusedVariables = false
weak.linter.flexible = false
weak.linter.style.longLine = false
weak.linter.style.whitespace = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "EconCSLib"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
name = "GCG24UserItemFairness"
srcDir = "papers"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
name = "DSWG24DiscretizationBias"
srcDir = "papers"

[[lean_lib]]
name = "MBJG25ProducerFairness"
srcDir = "papers"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
name = "ZL21TestOptionalPolicies"
srcDir = "papers"

[[lean_lib]]
name = "Roth82StableMatching"
srcDir = "papers"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
name = "GHW01DigitalGoods"
srcDir = "papers"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
srcDir = "papers"

[[lean_lib]]
name = "MSVV07AdWords"
srcDir = "papers"
