import LMMS04FairDivision.Theorem31QueryTranscript

open EconCSLib.FairDivision

namespace LMMS04FairDivision
namespace Theorem31

/-!
# LMMS Theorem 3.1: adaptive deterministic query transcripts

This file adds the adaptive-query seam missing from the fixed-query transcript
layer.  A deterministic adaptive algorithm chooses its next query from the
previous two-bit answers.  The transcript still lives in the same finite
`(Bool × Bool)^q` space, so the existing middle-pair counting argument applies
once we prove the source symmetry step: equal identical-profile transcripts
force equal swapped crossed-profile transcripts.
-/

/-- A length-`t` query history is just the prefix transcript of prior answers. -/
abbrev AdaptiveQueryHistory (Answer : Type*) (t : ℕ) :=
  QueryTranscript Answer t

/--
Deterministic adaptive query schedule.  At time `t`, the next query is a
function only of the previous `t` answers.
-/
structure AdaptiveQueryStrategy (Query Answer : Type*) where
  nextQuery : ∀ t : ℕ, AdaptiveQueryHistory Answer t → Query

namespace AdaptiveQueryStrategy

/-- Run a deterministic adaptive strategy against an answer oracle for `q` rounds. -/
def run {Query Answer : Type*} (strategy : AdaptiveQueryStrategy Query Answer) :
    (q : ℕ) → (Query → Answer) → QueryTranscript Answer q
  | 0, _ => fun t => nomatch t
  | q + 1, oracle => fun t =>
      if h : t.val < q then
        run strategy q oracle ⟨t.val, h⟩
      else
        oracle (strategy.nextQuery q (run strategy q oracle))

@[simp] theorem run_succ_of_lt {Query Answer : Type*}
    (strategy : AdaptiveQueryStrategy Query Answer)
    (oracle : Query → Answer) {q : ℕ} (t : Fin (q + 1))
    (h : t.val < q) :
    run strategy (q + 1) oracle t =
      run strategy q oracle ⟨t.val, h⟩ := by
  simp [run, h]

@[simp] theorem run_succ_last {Query Answer : Type*}
    (strategy : AdaptiveQueryStrategy Query Answer)
    (oracle : Query → Answer) (q : ℕ) :
    run strategy (q + 1) oracle ⟨q, Nat.lt_succ_self q⟩ =
      oracle (strategy.nextQuery q (run strategy q oracle)) := by
  simp [run]

/-- Equality of full `q + 1` adaptive transcripts implies equality of prefixes. -/
theorem run_prefix_eq_of_run_succ_eq {Query Answer : Type*}
    (strategy : AdaptiveQueryStrategy Query Answer)
    {oracle₁ oracle₂ : Query → Answer} {q : ℕ}
    (h :
      run strategy (q + 1) oracle₁ =
        run strategy (q + 1) oracle₂) :
    run strategy q oracle₁ = run strategy q oracle₂ := by
  funext t
  have ht :=
    congrFun h
      (⟨t.val, Nat.lt_trans t.isLt (Nat.lt_succ_self q)⟩ : Fin (q + 1))
  simpa [run, t.isLt] using ht

/-- Equality of full `q + 1` transcripts gives equality of the last answers. -/
theorem run_last_eq_of_run_succ_eq {Query Answer : Type*}
    (strategy : AdaptiveQueryStrategy Query Answer)
    {oracle₁ oracle₂ : Query → Answer} {q : ℕ}
    (h :
      run strategy (q + 1) oracle₁ =
        run strategy (q + 1) oracle₂) :
    oracle₁ (strategy.nextQuery q (run strategy q oracle₁)) =
      oracle₂ (strategy.nextQuery q (run strategy q oracle₂)) := by
  have ht := congrFun h (⟨q, Nat.lt_succ_self q⟩ : Fin (q + 1))
  simpa [run] using ht

/--
If two `q`-round prefixes agree and the next answers agree on the common next
query, then the `q + 1`-round adaptive transcripts agree.
-/
theorem run_succ_eq_of_prefix_eq_of_next_answer_eq {Query Answer : Type*}
    (strategy : AdaptiveQueryStrategy Query Answer)
    {oracle₁ oracle₂ : Query → Answer} {q : ℕ}
    (hprefix : run strategy q oracle₁ = run strategy q oracle₂)
    (hanswer :
      oracle₁ (strategy.nextQuery q (run strategy q oracle₁)) =
        oracle₂ (strategy.nextQuery q (run strategy q oracle₁))) :
    run strategy (q + 1) oracle₁ =
      run strategy (q + 1) oracle₂ := by
  funext t
  by_cases ht : t.val < q
  · have hprefix_t := congrFun hprefix (⟨t.val, ht⟩ : Fin q)
    simpa [run, ht] using hprefix_t
  · have htval : t.val = q := by
      omega
    have ht_eq : t = (⟨q, Nat.lt_succ_self q⟩ : Fin (q + 1)) := by
      ext
      exact htval
    subst t
    simpa [run, hprefix.symm] using hanswer

end AdaptiveQueryStrategy

/-- Two-bit oracle answer for a pair of source hard functions. -/
noncomputable def twoPlayerHardFunctionBoolOracle
    {Item : Type*} [Fintype Item] [DecidableEq Item] {k : ℕ}
    (u v : LMMS31HardFunction Item k) (S : Finset Item) : Bool × Bool :=
  (hardFunctionBoolAnswer u S, hardFunctionBoolAnswer v S)

/-- Adaptive two-player Boolean transcript generated by hard-function answers. -/
noncomputable def twoPlayerHardFunctionAdaptiveTranscript
    {Item : Type*} [Fintype Item] [DecidableEq Item] {k q : ℕ}
    (strategy : AdaptiveQueryStrategy (Finset Item) (Bool × Bool))
    (u v : LMMS31HardFunction Item k) :
    QueryTranscript (Bool × Bool) q :=
  strategy.run q (twoPlayerHardFunctionBoolOracle u v)

/--
Adaptive symmetry strengthening for the source hard family.  If the strategy
sees the same transcript on the identical profiles `(u,u)` and `(v,v)`, then
the identical and crossed transcripts all follow the same adaptive path.
-/
theorem twoPlayerHardFunctionAdaptiveTranscript_all_eq_of_identical_eq
    {Item : Type*} [Fintype Item] [DecidableEq Item] {k : ℕ}
    (strategy : AdaptiveQueryStrategy (Finset Item) (Bool × Bool))
    (q : ℕ) (u v : LMMS31HardFunction Item k)
    (hidentical :
      twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u =
        twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v v) :
    twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u =
        twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u v ∧
      twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u v =
        twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u ∧
      twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u =
        twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v v := by
  induction q with
  | zero =>
      simp [twoPlayerHardFunctionAdaptiveTranscript, AdaptiveQueryStrategy.run]
  | succ q ih =>
      have hrun_identical :
          strategy.run (q + 1) (twoPlayerHardFunctionBoolOracle u u) =
            strategy.run (q + 1) (twoPlayerHardFunctionBoolOracle v v) := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using hidentical
      have hprefix_identical :
          twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u =
            twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v v := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using
          AdaptiveQueryStrategy.run_prefix_eq_of_run_succ_eq
            (strategy := strategy) hrun_identical
      rcases ih hprefix_identical with ⟨huu_uv, huv_vu, hvu_vv⟩
      have hlast_identical :=
        AdaptiveQueryStrategy.run_last_eq_of_run_succ_eq
          (strategy := strategy) hrun_identical
      have hprefix_run :
          strategy.run q (twoPlayerHardFunctionBoolOracle u u) =
            strategy.run q (twoPlayerHardFunctionBoolOracle v v) := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using hprefix_identical
      have hsame_bool :
          hardFunctionBoolAnswer u
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) =
            hardFunctionBoolAnswer v
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) := by
        have hpair :
            twoPlayerHardFunctionBoolOracle u u
                (strategy.nextQuery q
                  (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) =
            twoPlayerHardFunctionBoolOracle v v
                (strategy.nextQuery q
                  (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) := by
          simpa [twoPlayerHardFunctionAdaptiveTranscript,
            hprefix_run.symm] using hlast_identical
        exact congrArg Prod.fst hpair
      have hanswer_uu_uv :
          twoPlayerHardFunctionBoolOracle u u
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) =
            twoPlayerHardFunctionBoolOracle u v
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u)) := by
        simp [twoPlayerHardFunctionBoolOracle, hsame_bool]
      have hanswer_uv_vu :
          twoPlayerHardFunctionBoolOracle u v
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u v)) =
            twoPlayerHardFunctionBoolOracle v u
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u v)) := by
        simpa [twoPlayerHardFunctionBoolOracle, hsame_bool, huu_uv.symm]
      have huu_vu :
          twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u =
            twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u :=
        huu_uv.trans huv_vu
      have hanswer_vu_vv :
          twoPlayerHardFunctionBoolOracle v u
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u)) =
            twoPlayerHardFunctionBoolOracle v v
              (strategy.nextQuery q
                (twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u)) := by
        simpa [twoPlayerHardFunctionBoolOracle, hsame_bool, huu_vu.symm]
      have huu_uv_succ :
          twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy u u =
            twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy u v := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using
          AdaptiveQueryStrategy.run_succ_eq_of_prefix_eq_of_next_answer_eq
            (strategy := strategy)
            (by simpa [twoPlayerHardFunctionAdaptiveTranscript] using huu_uv)
            hanswer_uu_uv
      have huv_vu_succ :
          twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy u v =
            twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy v u := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using
          AdaptiveQueryStrategy.run_succ_eq_of_prefix_eq_of_next_answer_eq
            (strategy := strategy)
            (by simpa [twoPlayerHardFunctionAdaptiveTranscript] using huv_vu)
            hanswer_uv_vu
      have hvu_vv_succ :
          twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy v u =
            twoPlayerHardFunctionAdaptiveTranscript (q := q + 1) strategy v v := by
        simpa [twoPlayerHardFunctionAdaptiveTranscript] using
          AdaptiveQueryStrategy.run_succ_eq_of_prefix_eq_of_next_answer_eq
            (strategy := strategy)
            (by simpa [twoPlayerHardFunctionAdaptiveTranscript] using hvu_vv)
            hanswer_vu_vv
      exact ⟨huu_uv_succ, huv_vu_succ, hvu_vv_succ⟩

/--
The adaptive analogue of the fixed-query swap lemma: equal identical-profile
transcripts imply equal crossed transcripts after swapping the players.
-/
theorem twoPlayerHardFunctionAdaptiveTranscript_swap_eq_of_identical_eq
    {Item : Type*} [Fintype Item] [DecidableEq Item] {k q : ℕ}
    (strategy : AdaptiveQueryStrategy (Finset Item) (Bool × Bool))
    (u v : LMMS31HardFunction Item k)
    (hidentical :
      twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u u =
        twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v v) :
    twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy u v =
      twoPlayerHardFunctionAdaptiveTranscript (q := q) strategy v u :=
  (twoPlayerHardFunctionAdaptiveTranscript_all_eq_of_identical_eq
    strategy q u v hidentical).2.1

namespace LMMS31MiddleComplementPairs

variable {Item : Type*} [Fintype Item] [DecidableEq Item] {k : ℕ}
variable (C : LMMS31MiddleComplementPairs Item k)

/--
Adaptive two-bit query lower bound for minimum envy.  The query schedule may
depend on all previous two-player Boolean answers.
-/
theorem minimum_envy_lower_bound_from_twoBit_adaptive_queries_of_two_mul_lt
    {q : ℕ}
    (hcard_items : Fintype.card Item = 2 * k)
    (strategy : AdaptiveQueryStrategy (Finset Item) (Bool × Bool))
    (output : QueryTranscript (Bool × Bool) q → Allocation LMMS31Agent Item)
    (hquery_bound : 2 * q < Fintype.card C.Pair) :
    ¬ ∀ choice₁ choice₂,
      MinimumReportEnvyAllocation
        (lmms31CrossReport
          (C.hardFunctionOfMiddleChoice choice₁)
          (C.hardFunctionOfMiddleChoice choice₂))
        (Finset.univ : Finset Item)
        (output
          (twoPlayerHardFunctionAdaptiveTranscript strategy
            (C.hardFunctionOfMiddleChoice choice₁)
            (C.hardFunctionOfMiddleChoice choice₂))) := by
  exact
    C.minimum_envy_lower_bound_from_twoBit_query_count_of_two_mul_lt
      hcard_items
      (fun choice =>
        twoPlayerHardFunctionAdaptiveTranscript strategy
          (C.hardFunctionOfMiddleChoice choice)
          (C.hardFunctionOfMiddleChoice choice))
      (fun choice₁ choice₂ =>
        twoPlayerHardFunctionAdaptiveTranscript strategy
          (C.hardFunctionOfMiddleChoice choice₁)
          (C.hardFunctionOfMiddleChoice choice₂))
      output hquery_bound
      (by
        intro choice₁ choice₂ hidentical
        exact
          twoPlayerHardFunctionAdaptiveTranscript_swap_eq_of_identical_eq
            strategy
            (C.hardFunctionOfMiddleChoice choice₁)
            (C.hardFunctionOfMiddleChoice choice₂)
            hidentical)

/--
Adaptive two-bit query lower bound for minimum envy ratio, using the same
source symmetry and transcript-count argument.
-/
theorem minimum_envy_ratio_lower_bound_from_twoBit_adaptive_queries_of_two_mul_lt
    {q : ℕ}
    (hcard_items : Fintype.card Item = 2 * k)
    (strategy : AdaptiveQueryStrategy (Finset Item) (Bool × Bool))
    (output : QueryTranscript (Bool × Bool) q → Allocation LMMS31Agent Item)
    (hquery_bound : 2 * q < Fintype.card C.Pair) :
    ¬ ∀ choice₁ choice₂,
      MinimumReportEnvyRatioAllocation
        (lmms31CrossReport
          (C.hardFunctionOfMiddleChoice choice₁)
          (C.hardFunctionOfMiddleChoice choice₂))
        (Finset.univ : Finset Item)
        (output
          (twoPlayerHardFunctionAdaptiveTranscript strategy
            (C.hardFunctionOfMiddleChoice choice₁)
            (C.hardFunctionOfMiddleChoice choice₂))) := by
  exact
    C.minimum_envy_ratio_lower_bound_from_twoBit_query_count_of_two_mul_lt
      hcard_items
      (fun choice =>
        twoPlayerHardFunctionAdaptiveTranscript strategy
          (C.hardFunctionOfMiddleChoice choice)
          (C.hardFunctionOfMiddleChoice choice))
      (fun choice₁ choice₂ =>
        twoPlayerHardFunctionAdaptiveTranscript strategy
          (C.hardFunctionOfMiddleChoice choice₁)
          (C.hardFunctionOfMiddleChoice choice₂))
      output hquery_bound
      (by
        intro choice₁ choice₂ hidentical
        exact
          twoPlayerHardFunctionAdaptiveTranscript_swap_eq_of_identical_eq
            strategy
            (C.hardFunctionOfMiddleChoice choice₁)
            (C.hardFunctionOfMiddleChoice choice₂)
            hidentical)

end LMMS31MiddleComplementPairs

end Theorem31
end LMMS04FairDivision
