import EconCSLean.Online.MainTheorems

/-!
# Paper-Facing Theorem Ledger

This file is the Lean-oriented audit surface for the AdWords paper formalization.
The file is declaration-oriented and ordered by paper flow.
Each entry is documented as a paper-facing theorem wrapper already defined in
`MainTheorems.lean`.
-/

namespace EconCSLean
namespace Online

-- 1) Core model and LP primitives

-- Finite AdWords instance with advertiser budgets and query bids.
#check AdWordsInstance

-- A concrete integral assignment map `Query → Option Advertiser` (`none` means no assignment).
#check AdWordsInstance.Assignment

-- A fractional LP assignment `Advertiser → Query → ℝ`.
#check AdWordsInstance.FractionalAssignment

-- Budget feasibility and related LP predicates used throughout the paper.
#check AdWordsInstance.Feasible
#check AdWordsInstance.FractionalFeasible
#check AdWordsInstance.ChoiceRuleFeasible
#check AdWordsInstance.StateInvariant

-- The finite offline benchmark: integral and fractional value terms.
#check AdWordsInstance.offlineOptimumAssignment
#check AdWordsInstance.offlineOptimumValue
#check AdWordsInstance.revenue
#check AdWordsInstance.fractionalRevenue

-- Dual LP side: `dualObjective α β` and `DualFeasible α β`.
#check AdWordsInstance.DualFeasible
#check AdWordsInstance.dualObjective

-- LP setup and weak duality wrappers.
#check paper_adwords_empty_assignment_feasible
#check paper_adwords_offline_optimum_exists
#check paper_adwords_revenue_le_total_budget_of_feasible
#check paper_adwords_lp_weak_duality
#check paper_adwords_integral_assignment_fractional_feasible
#check paper_adwords_fractional_lp_weak_duality

-- Slack and max-slack dual constructors used in the Balance/MSVV reduction.
#check paper_adwords_dual_feasible_of_slack_score_bound
#check paper_adwords_dual_feasible_max_slack_beta
#check paper_adwords_dual_feasible_msvv_assignment
#check paper_adwords_dual_feasible_msvv_normalized_assignment

-- Choice rule existence and basic online run feasibility.
#check paper_adwords_balance_choice_exists
#check paper_adwords_run_assignment_feasible
#check paper_adwords_balance_run_assignment_feasible

-- 2) Online semantics and history accounting

-- The online run history state and assignment unfold.
#check AdWordsInstance.HistoryState
#check AdWordsInstance.historyFinset
#check AdWordsInstance.initialHistoryState
#check AdWordsInstance.stepHistoryState
#check AdWordsInstance.runHistoryState
#check AdWordsInstance.runHistoryStateFrom
#check AdWordsInstance.runAssignment

-- History-local properties used by the proof.
#check paper_adwords_balance_assignment_assigned_only_from_history
#check paper_adwords_spend_monotone_over_history
#check paper_adwords_run_revenue_eq_history_revenue_charge
#check paper_adwords_balance_charge_le_run_revenue

-- 3) Per-query dual charge lemmas

-- Final slack-score and beta bound lemmas for admissible/exhausted advertisers.
#check paper_adwords_final_slack_score_le_initial_balance_score
#check paper_adwords_max_slack_beta_le_balance_score_of_all_can_assign
#check paper_adwords_msvv_ratio_mul_normalized_max_slack_beta_le_balance_score_of_all_can_assign
#check paper_adwords_blocked_advertiser_final_alpha_ge_exp_neg_epsilon
#check paper_adwords_blocked_advertiser_final_slack_score_le_error
#check paper_adwords_msvv_ratio_mul_blocked_advertiser_normalized_final_slack_score_le_error
#check paper_adwords_msvv_ratio_mul_normalized_max_slack_beta_le_balance_score_add_max_bid_error
#check paper_adwords_max_slack_beta_le_balance_score_or_max_bid_error
#check paper_adwords_max_slack_beta_le_balance_score_add_max_bid_error

-- Summed and normalized query-dual bounds over histories.
#check paper_adwords_balance_history_max_slack_beta_sum_le_charge_add_error
#check paper_adwords_balance_query_dual_sum_le_charge_add_error_of_history_cover
#check paper_adwords_msvv_ratio_mul_normalized_query_dual_sum_le_charge_add_error_of_history_cover

-- 4) Small-bids bridge and section-6/8 reductions

-- Blocking-advertiser spent-fraction bound under ε-small bids.
#check paper_adwords_small_bids_blocked_advertiser_spent_fraction

-- Effective-bid transformation wrappers: small-bids preserved by each mapping.
#check paper_adwords_effective_bids_small_bids
#check paper_adwords_click_through_rates_small_bids
#check paper_adwords_weighted_bids_small_bids
#check paper_adwords_availability_small_bids
#check paper_adwords_multiple_slots_small_bids
#check AdWordsInstance.withEffectiveBids
#check AdWordsInstance.withClickThroughRates
#check AdWordsInstance.withAdvertiserWeights
#check AdWordsInstance.withAvailability
#check AdWordsInstance.withSlots
#check AdWordsInstance.withSlotsPerPageDistinct
#check AdWordsInstance.withSlotsDistinctChoice

-- 5) Section-7 lower-bound reductions

-- Primitive reduction chain from paper certificates to lower-bound claim.
#check paper_adwords_theorem9_no_randomized_algorithm_beats_msvv_ratio_of_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_msvv_ratio_of_permutation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_revenue_bound_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_round_allocation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_pointwise_allocation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_symmetric_pointwise_allocation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_relabel_symmetric_pointwise_allocation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_observed_prefix_allocation_certificate
#check paper_adwords_theorem9_no_randomized_algorithm_beats_ratio_of_feasible_observed_prefix_allocation_certificate
#check paper_adwords_theorem9_harmonic_layer_count_bound_of_log_spend_cap
#check paper_adwords_theorem9_bidder_spend_upper_bound_le_log_tail
#check paper_adwords_theorem9_harmonic_layer_count_bound
#check paper_adwords_theorem9_normalized_revenue_upper_bound_le_msvv_ratio_add_grid_errors
#check paper_adwords_theorem9_harmonic_eventually_le_msvv_ratio_add_delta_of_layer_count_bound
#check paper_adwords_theorem9_harmonic_eventually_le_msvv_ratio_add_delta
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_pointwise_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_symmetric_pointwise_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_relabel_symmetric_pointwise_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_observed_prefix_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_feasible_observed_prefix_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_feasible_prefix_rule_family
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_integral_prefix_choice_family
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_integral_prefix_choice_family_of_realized_revenue
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_integral_prefix_algorithms
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_integral_prefix_algorithms_of_realized_revenue
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_layer_count_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_pointwise_layer_count_family_certificate
#check paper_adwords_theorem9_eventually_no_randomized_algorithm_beats_msvv_ratio_add_delta_of_symmetric_pointwise_layer_count_family_certificate

-- 6) Main Balance/MSVV primal-dual and approximation chain

-- Primal-dual template wrappers used by the finite and asymptotic analyses.
#check paper_adwords_competitive_of_primal_dual_certificate
#check paper_adwords_balance_msvv_competitive_of_primal_dual_certificate
#check paper_adwords_balance_msvv_objective_bound_of_history_accounting
#check paper_adwords_balance_msvv_competitive_of_objective_bound
#check paper_adwords_balance_msvv_approx_objective_bound_of_history_accounting
#check paper_adwords_balance_msvv_approx_competitive_of_approx_objective_bound
#check paper_adwords_balance_msvv_history_approx_accounting_with_explicit_error
#check paper_adwords_balance_msvv_approx_objective_bound_with_explicit_error
#check paper_adwords_balance_msvv_approx_competitive_with_explicit_history_error
#check paper_adwords_balance_msvv_approx_competitive_with_error_bound
#check paper_adwords_balance_msvv_approx_competitive_with_query_sum_error_bound
#check paper_adwords_balance_msvv_finRange_approx_competitive_with_query_sum_error_bound
#check paper_adwords_balance_msvv_approx_competitive_up_to_delta
#check paper_adwords_balance_msvv_finRange_approx_competitive_up_to_delta
#check paper_adwords_balance_msvv_approx_competitive_up_to_delta_of_small_bids_threshold
#check paper_adwords_balance_msvv_finRange_approx_competitive_up_to_delta_of_small_bids_threshold
#check paper_adwords_balance_msvv_competitive_of_arbitrarily_small_bids_threshold
#check paper_adwords_balance_msvv_finRange_competitive_of_arbitrarily_small_bids_threshold
#check paper_adwords_balance_msvv_finRange_family_eventually_up_to_delta
#check paper_adwords_balance_msvv_finRange_family_eventually_up_to_delta_of_small_bids_threshold
#check paper_adwords_balance_msvv_finRange_family_limit_competitive_of_error_eventually
#check paper_adwords_balance_msvv_finRange_family_limit_competitive_of_small_bids_threshold
#check paper_adwords_balance_msvv_finRange_family_limit_competitive_of_error_eventually_of_offline_opt_convergence
#check paper_adwords_balance_msvv_finRange_family_limit_competitive_of_small_bids_threshold_of_offline_opt_convergence
#check paper_adwords_balance_msvv_competitive_of_small_bids_limit_family

end Online
end EconCSLean
