import EconCSLib.MechanismDesign.Auctions.MainTheorems

/-!
# Paper-Facing Theorems: Competitive Auctions and Digital Goods

This folder owns the Goldberg-Hartline-Wright 2001 digital-goods track. The
closed Lean statements currently live in the reusable auction library; this file
re-exports only the digital-goods surface under the citation-specific namespace.
-/

namespace GHW01DigitalGoods

export EconCSLib.Auction (
  paper_digital_goods_revenue
  paper_digital_goods_revenue_eq
  paper_digital_goods_truthful
  paper_digital_goods_truthful_eq
  paper_two_winner_benchmark
  paper_two_winner_benchmark_eq
  paper_posted_price_truthful
  paper_posted_price_individually_rational
  paper_posted_price_no_positive_transfers
  paper_posted_price_revenue_eq_single_price
  paper_threshold_price_truthful
  paper_own_erased_threshold_price_truthful
  paper_cross_sample_candidate_threshold_truthful
  paper_cross_sample_candidate_offer_threshold_truthful
  paper_cross_sample_candidate_offer_no_positive_transfers
  paper_average_cross_sample_candidate_offer_revenue_nonneg
  paper_cross_sample_offer_competitive_of_certificate
  paper_theorem6_2_random_sampling_union_bound
  paper_finite_candidate_fixed_price_benchmark_nonneg
  paper_single_price_revenue_le_candidate_benchmark_of_feasible
  paper_two_winner_fixed_price_benchmark
  paper_theorem4_1_fixed_price_lower_bound_of_factor_two_bin
  paper_theorem4_1_fixed_price_lower_bound_of_factor_two_partition
  paper_corollary4_2_fixed_price_lower_bound_from_truncation
  paper_theorem7_1_weighted_pairing_square_sum_endpoint
  paper_threshold_price_individually_rational
  paper_threshold_price_no_positive_transfers
  paper_lemma8_1_truthful_win_probability_monotone
  paper_lemma8_1_allocation_mono_own_bid_of_truthful
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_certificate
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_monotone_probabilities
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_gain_bounds
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_adjacent_gain_recursion
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_truthful_cost_comparisons
  paper_theorem9_1_bid_independent_threshold_transition
  paper_theorem9_1_transition_witness_revenue_bound
  paper_theorem9_1_start_high_witness_revenue_bound
  paper_theorem9_1_two_value_bid_independent_lower_bound
  paper_theorem9_1_arbitrary_threshold_bid_independent_lower_bound
  paper_theorem9_1_arbitrary_threshold_scaled_lower_bound
)

end GHW01DigitalGoods
