import EconCSLib.MechanismDesign.Auctions.MainTheorems

/-!
# Paper-Facing Theorems: Competitive Auctions and Digital Goods

This folder owns the Goldberg-Hartline-Wright 2001 digital-goods track. The
closed Lean statements currently live in the reusable auction library; this file
re-exports only the digital-goods surface under the citation-specific namespace.
-/

namespace GHW01DigitalGoods

export EconCSLib.Auction (
  paper_digital_goods_revenue
  paper_digital_goods_revenue_eq
  paper_digital_goods_truthful
  paper_digital_goods_truthful_eq
  paper_two_winner_benchmark
  paper_two_winner_benchmark_eq
  paper_posted_price_truthful
  paper_posted_price_individually_rational
  paper_posted_price_no_positive_transfers
  paper_posted_price_revenue_eq_single_price
  paper_threshold_price_truthful
  paper_own_erased_threshold_price_truthful
  paper_cross_sample_candidate_threshold_truthful
  paper_cross_sample_candidate_offer_threshold_truthful
  paper_cross_sample_candidate_offer_no_positive_transfers
  paper_average_cross_sample_candidate_offer_revenue_nonneg
  paper_cross_sample_offer_competitive_of_certificate
  totalBidValue
  weightedPairingExpectedPayment
  weightedPairingExpectedRevenue
  weightedPairingExpectedRevenue_eq_sum_payments
  paper_theorem6_2_random_sampling_union_bound
  paper_theorem6_2_random_sampling_measure_union_bound
  paper_theorem6_2_sample_benchmark_from_sampled_winners
  paper_theorem6_2_original_revenue_le_three_sample_benchmark
  paper_theorem6_2_cross_sample_revenue_from_opposite_side
  paper_theorem6_2_sample_benchmark_le_two_cross_sample_revenue
  paper_theorem6_2_deterministic_six_revenue_bound
  paper_theorem6_2_deterministic_six_revenue_bound_of_large_sale_count
  paper_aux_theorem6_2_half_mean_indicator_lower_tail
  paper_aux_theorem6_2_fair_coin_lower_tail
  paper_aux_theorem6_2_fair_coin_lower_tail_relaxed
  paper_aux_theorem6_2_side_sale_bad_sample_le_exp
  paper_aux_theorem6_2_side_sale_sample_good_probability
  paper_aux_theorem6_2_fixed_price_revenue_bad_le_exp
  paper_aux_theorem6_2_fixed_price_revenue_good_probability
  paper_aux_theorem6_2_revenue_good_probability_by_candidate_union
  paper_aux_theorem6_2_selected_price_bad_large_sample_subset_top_prefix_union
  paper_aux_theorem6_2_selected_price_bad_large_sample_top_prefix_union
  paper_aux_theorem6_2_top_prefix_exp_sum_le_forty
  paper_aux_theorem6_2_selected_price_bad_large_sample_top_prefix_le_exp
  paper_aux_theorem6_2_selected_offer_large_sample_count_of_alpha_h
  paper_theorem6_2_fair_coin_revenue_bound_top_prefix_of_selected_large
  paper_theorem6_2_fair_coin_revenue_bound_top_prefix_alpha_h
  paper_theorem6_2_fair_coin_revenue_bound_top_prefix_alpha_h_fin_sorted
  paper_theorem6_2_fair_coin_revenue_bound_of_revenue_good_probability
  paper_theorem6_2_fair_coin_revenue_bound_candidate_union
  paper_finite_candidate_fixed_price_benchmark_nonneg
  paper_single_price_revenue_le_candidate_benchmark_of_feasible
  paper_two_winner_fixed_price_benchmark
  paper_theorem4_1_fixed_price_lower_bound_of_factor_two_bin
  paper_theorem4_1_fixed_price_lower_bound_of_factor_two_partition
  paper_corollary4_2_fixed_price_lower_bound_from_truncation
  paper_theorem7_1_weighted_pairing_square_sum_endpoint
  paper_theorem7_1_active_total_from_singleton_loss
  paper_theorem7_1_weighted_pairing_from_bin_square_revenue
  paper_theorem7_1_bin_revenue_lower_bound_algebra
  paper_theorem7_1_bin_raw_lower_bound_from_ranked_pairing_payments
  paper_theorem7_1_ranked_payment_pointwise_lower_bound
  paper_theorem7_1_factor_two_bin_price_floor
  paper_theorem7_1_factor_two_bin_price_floor_nonneg
  paper_theorem7_1_factor_two_bin_win_mass_bound
  paper_theorem7_1_factor_two_bin_delete_one_third
  paper_theorem7_1_same_bin_pair_probability_lower_bound
  paper_theorem7_1_weighted_pairing_from_active_bin_certificates
  paper_theorem7_1_weighted_pairing_from_ranked_bin_payment_certificates
  paper_theorem7_1_weighted_pairing_from_ranked_bin_structural_certificates
  paper_theorem7_1_factor_two_denominator_positive
  paper_theorem7_1_weighted_pairing_from_factor_two_bin_certificates
  paper_theorem7_1_ranked_bin_double_sum_le_weighted_pairing_revenue
  paper_theorem7_1_weighted_pairing_from_factor_two_ranked_bins
  paper_theorem7_1_weighted_pairing_from_factor_two_ranked_bins_of_value_bound
  paper_theorem7_1_weighted_pairing_from_factor_two_ranked_bins_of_value_bounds
  paper_threshold_price_individually_rational
  paper_threshold_price_no_positive_transfers
  paper_lemma8_1_truthful_win_probability_monotone
  paper_lemma8_1_allocation_mono_own_bid_of_truthful
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_certificate
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_monotone_probabilities
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_gain_bounds
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_adjacent_gain_recursion
  paper_theorem8_2_expected_revenue_le_fixed_price_benchmark_of_truthful_cost_comparisons
  paper_theorem9_1_bid_independent_threshold_transition
  paper_theorem9_1_transition_witness_revenue_bound
  paper_theorem9_1_start_high_witness_revenue_bound
  paper_theorem9_1_two_value_bid_independent_lower_bound
  paper_theorem9_1_arbitrary_threshold_bid_independent_lower_bound
  paper_theorem9_1_arbitrary_threshold_scaled_lower_bound
  paper_theorem9_1_count_threshold_revenue_eq_concrete_auction
  paper_theorem9_1_ratio_le_one_over_h_of_mul_revenue_le_benchmark
  paper_lemma9_2_deterministic_offer_payment_constant
  paper_lemma9_2_deterministic_offer_winning_monotone
  paper_lemma9_2_deterministic_offer_losing_prefix
  paper_lemma9_2_deterministic_offer_bid_independent
  paper_lemma9_2_deterministic_truthful_auction_bid_independent_slices
  paper_theorem9_3_deterministic_truthful_lower_bound_of_count_threshold
)

end GHW01DigitalGoods
