import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Tactic.NormNum

open scoped BigOperators

namespace EconCSLean
namespace Auction

/--
A finite position-auction environment.

`clickThroughRate s` is the expected number of clicks generated by slot `s`.
The GSP Test-of-Time papers specialize this structure to ordered sponsored
search slots with weakly decreasing click-through rates.
-/
structure PositionEnvironment (Slot : Type*) where
  clickThroughRate : Slot → ℝ

/--
An outcome for a position auction: each bidder is either assigned a slot or left
unassigned, and each bidder has a per-click payment.
-/
structure PositionOutcome (Bidder Slot : Type*) where
  slotOf : Bidder → Option Slot
  paymentPerClick : Bidder → ℝ

namespace PositionOutcome

variable {Bidder Slot : Type*}

/-- Quasilinear expected utility in a position auction. -/
def utility (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) : ℝ :=
  match O.slotOf i with
  | none => 0
  | some s => E.clickThroughRate s * (values i - O.paymentPerClick i)

/-- Expected revenue contribution from one bidder. -/
def revenueContribution (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (i : Bidder) : ℝ :=
  match O.slotOf i with
  | none => 0
  | some s => E.clickThroughRate s * O.paymentPerClick i

/-- Total expected revenue. -/
noncomputable def revenue [Fintype Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot) : ℝ :=
  ∑ i : Bidder, revenueContribution E O i

/-- Total expected allocative welfare. -/
noncomputable def welfare [Fintype Bidder]
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : ℝ :=
  ∑ i : Bidder,
    match O.slotOf i with
    | none => 0
    | some s => E.clickThroughRate s * values i

/-- No slot is assigned to two different bidders. -/
def FeasibleAssignment (O : PositionOutcome Bidder Slot) : Prop :=
  ∀ ⦃i j : Bidder⦄ ⦃s : Slot⦄,
    O.slotOf i = some s → O.slotOf j = some s → i = j

theorem utility_eq_zero_of_unassigned
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) {i : Bidder}
    (hslot : O.slotOf i = none) :
    utility E O values i = 0 := by
  simp [utility, hslot]

theorem revenue_nonneg [Fintype Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (hctr : ∀ s, 0 ≤ E.clickThroughRate s)
    (hpay : ∀ i, 0 ≤ O.paymentPerClick i) :
    0 ≤ revenue E O := by
  classical
  unfold revenue
  exact Finset.sum_nonneg fun i _ => by
    cases hslot : O.slotOf i with
    | none =>
        simp [revenueContribution, hslot]
    | some s =>
        simpa [revenueContribution, hslot] using
          mul_nonneg (hctr s) (hpay i)

end PositionOutcome

/-! ## Position mechanisms and equilibrium predicates -/

/-- A position mechanism maps bid profiles to position outcomes. -/
abbrev PositionMechanism (Bidder Slot : Type*) :=
  (Bidder → ℝ) → PositionOutcome Bidder Slot

namespace PositionMechanism

variable {Bidder Slot : Type*}

/-- Utility induced by a position mechanism at a bid profile. -/
def utility (E : PositionEnvironment Slot)
    (M : PositionMechanism Bidder Slot)
    (values bids : Bidder → ℝ) (i : Bidder) : ℝ :=
  (M bids).utility E values i

/-- Dominant-strategy truthfulness for one-dimensional position-auction bids. -/
def TruthfulDominantStrategy [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot) : Prop :=
  ∀ (values : Bidder → ℝ) (i : Bidder) (report : ℝ),
    utility E M values (Function.update values i report) i ≤
      utility E M values values i

/-- Pure Nash equilibrium of a position-auction bidding game. -/
def IsNashEquilibrium [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot)
    (values bids : Bidder → ℝ) : Prop :=
  ∀ (i : Bidder) (report : ℝ),
    utility E M values (Function.update bids i report) i ≤
      utility E M values bids i

end PositionMechanism

/-! ## Position-outcome envy predicates -/

namespace PositionOutcome

variable {Bidder Slot : Type*}

/--
No bidder prefers another bidder's assigned slot at that other bidder's
per-click payment. This is the outcome-level envy-freeness predicate used as a
building block for GSP equilibrium analyses.
-/
def SlotEnvyFree (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : Prop :=
  ∀ (i j : Bidder) (s : Slot),
    O.slotOf j = some s →
      E.clickThroughRate s * (values i - O.paymentPerClick j) ≤
        O.utility E values i

theorem slotEnvyFree_own_comparison
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (h : O.SlotEnvyFree E values) :
    ∀ (i : Bidder) (s : Slot),
      O.slotOf i = some s →
        E.clickThroughRate s * (values i - O.paymentPerClick i) ≤
          O.utility E values i := by
  intro i s hslot
  exact h i i s hslot

end PositionOutcome

/-!
## A small GSP non-truthfulness witness

The 2018 SIGecom Test-of-Time award recognized the first analyses of GSP-style
position auctions.  A basic reason these papers are needed is that GSP is not a
truthful mechanism.  The following concrete three-bidder/two-slot outcome is a
minimal reusable witness: bidder `0` has value `10`, receives the top slot and
pays `8` per click when bidding truthfully, but can lower her bid to receive the
second slot and pay only `1` per click.  With click-through rates `1` and `1/2`,
that deviation improves utility from `2` to `9/2`.
-/

noncomputable def gspCounterexampleEnvironment : PositionEnvironment (Fin 2) where
  clickThroughRate s := if s = (0 : Fin 2) then 1 else 1 / 2

def gspCounterexampleValues : Fin 3 → ℝ :=
  fun i => if i = (0 : Fin 3) then 10 else if i = (1 : Fin 3) then 8 else 1

/--
Truthful GSP-style next-price outcome for values/bids `(10, 8, 1)`.
Bidder `0` wins slot `0` and pays bidder `1`'s bid.
-/
def gspCounterexampleTruthfulOutcome : PositionOutcome (Fin 3) (Fin 2) where
  slotOf i :=
    if i = (0 : Fin 3) then some (0 : Fin 2)
    else if i = (1 : Fin 3) then some (1 : Fin 2)
    else none
  paymentPerClick i :=
    if i = (0 : Fin 3) then 8
    else if i = (1 : Fin 3) then 1
    else 0

/--
GSP-style next-price outcome after bidder `0` lowers her bid below bidder `1`
but above bidder `2`.  Bidder `0` receives slot `1` and pays bidder `2`'s bid.
-/
def gspCounterexampleLowerBidOutcome : PositionOutcome (Fin 3) (Fin 2) where
  slotOf i :=
    if i = (1 : Fin 3) then some (0 : Fin 2)
    else if i = (0 : Fin 3) then some (1 : Fin 2)
    else none
  paymentPerClick i :=
    if i = (1 : Fin 3) then 7
    else if i = (0 : Fin 3) then 1
    else 0

/--
A minimal GSP-style mechanism sufficient to expose the profitable deviation in
the counterexample. If bidder `0` bids below bidder `1`, bidder `0` receives the
second slot and pays bidder `2`'s bid; otherwise bidder `0` receives the top
slot and pays bidder `1`'s bid.
-/
noncomputable def gspCounterexampleMechanism :
    PositionMechanism (Fin 3) (Fin 2) :=
  fun bids =>
    if bids (0 : Fin 3) < bids (1 : Fin 3) then
      gspCounterexampleLowerBidOutcome
    else
      gspCounterexampleTruthfulOutcome

theorem gspCounterexample_truthfulUtility_bidder0 :
    gspCounterexampleTruthfulOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) = 2 := by
  norm_num [PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleTruthfulOutcome]

theorem gspCounterexample_lowerBidUtility_bidder0 :
    gspCounterexampleLowerBidOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) = 9 / 2 := by
  norm_num [PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleLowerBidOutcome]

/--
Concrete witness that GSP-style position auctions are not dominant-strategy
truthful: bidder `0` benefits by lowering her bid in this two-slot instance.
-/
theorem gspCounterexample_lowerBid_profitable :
    gspCounterexampleTruthfulOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) <
    gspCounterexampleLowerBidOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) := by
  rw [gspCounterexample_truthfulUtility_bidder0,
    gspCounterexample_lowerBidUtility_bidder0]
  norm_num

theorem gspCounterexampleMechanism_truthfulUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gspCounterexampleMechanism
      gspCounterexampleValues gspCounterexampleValues (0 : Fin 3) = 2 := by
  norm_num [PositionMechanism.utility, gspCounterexampleMechanism,
    PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleTruthfulOutcome]

theorem gspCounterexampleMechanism_lowerBidUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gspCounterexampleMechanism
      gspCounterexampleValues
      (Function.update gspCounterexampleValues (0 : Fin 3) 7)
      (0 : Fin 3) = 9 / 2 := by
  norm_num [PositionMechanism.utility, gspCounterexampleMechanism,
    PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleLowerBidOutcome,
    Function.update]

/--
Mechanism-level version of the GSP counterexample: truthful bidding is not a
dominant strategy for this two-slot GSP-style mechanism.
-/
theorem gspCounterexampleMechanism_not_truthful :
    ¬ PositionMechanism.TruthfulDominantStrategy
      gspCounterexampleEnvironment gspCounterexampleMechanism := by
  intro htruth
  have hle := htruth gspCounterexampleValues (0 : Fin 3) 7
  rw [gspCounterexampleMechanism_lowerBidUtility_bidder0,
    gspCounterexampleMechanism_truthfulUtility_bidder0] at hle
  norm_num at hle

end Auction
end EconCSLean
